{"payload":{"allShortcutsEnabled":true,"fileTree":{"report":{"items":[{"name":"prelim_analysis","path":"report/prelim_analysis","contentType":"directory"},{"name":"README.md","path":"report/README.md","contentType":"file"},{"name":"final_report.html","path":"report/final_report.html","contentType":"file"},{"name":"final_report.qmd","path":"report/final_report.qmd","contentType":"file"}],"totalCount":4},"":{"items":[{"name":"data","path":"data","contentType":"directory"},{"name":"figures","path":"figures","contentType":"directory"},{"name":"peer_review","path":"peer_review","contentType":"directory"},{"name":"presentation","path":"presentation","contentType":"directory"},{"name":"proposal","path":"proposal","contentType":"directory"},{"name":"report","path":"report","contentType":"directory"},{"name":"scripts","path":"scripts","contentType":"directory"},{"name":".gitignore","path":".gitignore","contentType":"file"},{"name":"README.md","path":"README.md","contentType":"file"},{"name":"README.qmd","path":"README.qmd","contentType":"file"},{"name":"final-project-group-8-1.Rproj","path":"final-project-group-8-1.Rproj","contentType":"file"}],"totalCount":11}},"fileTreeProcessingTime":8.143454,"foldersToFetch":[],"reducedMotionEnabled":"system","repo":{"id":609270862,"defaultBranch":"main","name":"final-project-group-8-1","ownerLogin":"hoellers-vassar-classes","currentUserCanPush":true,"isFork":false,"isEmpty":false,"createdAt":"2023-03-03T13:32:11.000-05:00","ownerAvatar":"https://avatars.githubusercontent.com/u/123032550?v=4","public":false,"private":true,"isOrgOwned":true},"symbolsExpanded":false,"treeExpanded":true,"refInfo":{"name":"main","listCacheKey":"v0:1677869448.035344","canEdit":true,"refType":"branch","currentOid":"05a9f992210ebb022477a34cebea6fd87ab40326"},"path":"report/final_report.html","currentUser":{"id":123203156,"login":"sawouda2003","userEmail":"sawouda@vassar.edu"},"blob":{"rawLines":["<!DOCTYPE html>","<html xmlns=\"http://www.w3.org/1999/xhtml\" lang=\"en\" xml:lang=\"en\"><head>","","<meta charset=\"utf-8\">","<meta name=\"generator\" content=\"quarto-1.2.335\">","","<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=yes\">","","<meta name=\"author\" content=\"Group 8\">","<meta name=\"dcterms.date\" content=\"2023-05-02\">","","<title>Sweet Victory: Predicting A Halloween Candy’s Popularity based on its Attributes</title>","<style>","code{white-space: pre-wrap;}","span.smallcaps{font-variant: small-caps;}","div.columns{display: flex; gap: min(4vw, 1.5em);}","div.column{flex: auto; overflow-x: auto;}","div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}","ul.task-list{list-style: none;}","ul.task-list li input[type=\"checkbox\"] {","  width: 0.8em;","  margin: 0 0.8em 0.2em -1.6em;","  vertical-align: middle;","}","</style>","","","<script src=\"final_report_files/libs/clipboard/clipboard.min.js\"></script>","<script src=\"final_report_files/libs/quarto-html/quarto.js\"></script>","<script src=\"final_report_files/libs/quarto-html/popper.min.js\"></script>","<script src=\"final_report_files/libs/quarto-html/tippy.umd.min.js\"></script>","<script src=\"final_report_files/libs/quarto-html/anchor.min.js\"></script>","<link href=\"final_report_files/libs/quarto-html/tippy.css\" rel=\"stylesheet\">","<link href=\"final_report_files/libs/quarto-html/quarto-syntax-highlighting.css\" rel=\"stylesheet\" id=\"quarto-text-highlighting-styles\">","<script src=\"final_report_files/libs/bootstrap/bootstrap.min.js\"></script>","<link href=\"final_report_files/libs/bootstrap/bootstrap-icons.css\" rel=\"stylesheet\">","<link href=\"final_report_files/libs/bootstrap/bootstrap.min.css\" rel=\"stylesheet\" id=\"quarto-bootstrap\" data-mode=\"light\">","","  <script src=\"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js\" type=\"text/javascript\"></script>","","</head>","","<body class=\"fullcontent\">","","<div id=\"quarto-content\" class=\"page-columns page-rows-contents page-layout-article\">","","<main class=\"content\" id=\"quarto-document-content\">","","<header id=\"title-block-header\" class=\"quarto-title-block default\">","<div class=\"quarto-title\">","<h1 class=\"title\">Sweet Victory: Predicting A Halloween Candy’s Popularity based on its Attributes</h1>","</div>","","","","<div class=\"quarto-title-meta\">","","    <div>","    <div class=\"quarto-title-meta-heading\">Author</div>","    <div class=\"quarto-title-meta-contents\">","             <p>Group 8 </p>","          </div>","  </div>","    ","    <div>","    <div class=\"quarto-title-meta-heading\">Published</div>","    <div class=\"quarto-title-meta-contents\">","      <p class=\"date\">May 2, 2023</p>","    </div>","  </div>","  ","    ","  </div>","  ","","</header>","","<section id=\"introduction-and-data\" class=\"level2\">","<h2 class=\"anchored\" data-anchor-id=\"introduction-and-data\">Introduction and Data</h2>","<p>Halloween is objectively the best time of the year. This glorious season is marked by spooky decor, scary movies on television and in theaters, crisp fall weather, and of course, candy. Whether gobbled up in earnest by children or secretly by adults, Halloween candy is a massive benefit to spooky season, but which Halloween candy is the greatest of them all?</p>","<p>While everyone has their own tastes, in October of 2017, FiveThirtyEight writer Walt Hickey tasked himself with answering this question objectively. Through an online knockout bracket between various popular Halloween candies, Hickey surveyed over 8000 IP addresses on 269,000 matchups. We cannot assume that this translated to 8000 people, as it’s impossible to tell if more than one person shares an IP address) with over 269,000 choices - an average of about 33 per address. Sadly, the raw data sourced from the survey itself could not be sourced. Instead, we are provided with the results of Hickey’s preliminary analysis, sorted by candy brand.</p>","<p>The details of the knockout bracket are as follows: One user (marked by their computer’s IP address) is presented with two randomly selected fun-sized candy options and asked “Which would you prefer as a trick-or-treater?” The participant can either choose one of the two candies or choose to skip the question altogether, with no limit on the amount of responses one IP address can give. However, it is unlikely that any single participant significantly skewed the results, as it would take 3655 responses to give one’s opinion about <em>every</em> candy combination. Quoth Hickey: <em>“We don’t really need to care about the, say, hardcore Hershey fans attempting to rig the sample, because in order for someone to seriously dent their candy’s outcome, they’d have to go through scores of irrelevant matchups.”</em></p>","<p>His results were outlined in a 2017 FiveThirtyEight article titled ‘The Ultimate Candy Power Ranking’, and posted to Github on Halloween of that same year. The data, organized by specific candy, details that candy’s attributes (set as a series of 13 binary categorical variables), its price relative to its opponents, its sugar percentage, and its performance in the bracket. More specific information is given in the following codebook:</p>","<div class=\"cell\">","","</div>","<div class=\"cell\">","<div class=\"cell-output-display\">","<table class=\"table table-sm table-striped\">","<caption>Codebook </caption>","<thead>","<tr class=\"header\">","<th style=\"text-align: left;\">Variable</th>","<th style=\"text-align: left;\">Explanation</th>","</tr>","</thead>","<tbody>","<tr class=\"odd\">","<td style=\"text-align: left;\">competitorname</td>","<td style=\"text-align: left;\">The name of the candy</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">chocolate</td>","<td style=\"text-align: left;\">Does it contain chocolate?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">fruity</td>","<td style=\"text-align: left;\">Is it fruit flavored?</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">caramel</td>","<td style=\"text-align: left;\">Does it contain caramel?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">peanutyalmondy</td>","<td style=\"text-align: left;\">Does it contain nuts, or a nutty flavor?</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">nougat</td>","<td style=\"text-align: left;\">Does it contain nougat?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">crispedricewafer</td>","<td style=\"text-align: left;\">Does it contain a ‘crunch’ factor, like crisped rice or a wafer?</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">hard</td>","<td style=\"text-align: left;\">Is it a hard candy?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">bar</td>","<td style=\"text-align: left;\">Is it a candy bar?</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">pluribus</td>","<td style=\"text-align: left;\">Does it come in multiple pieces, like Skittles or M&amp;Ms?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">sugarpercent</td>","<td style=\"text-align: left;\">The percentile of sugar as it falls under within the data set.</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">pricepercent</td>","<td style=\"text-align: left;\">The unit price percentile compared to the rest of the set.</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">winpercent</td>","<td style=\"text-align: left;\">The overall win percentage according to 269,000 matchups.</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">sour</td>","<td style=\"text-align: left;\">Is it sour?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">shaped</td>","<td style=\"text-align: left;\">Is it an interesting shape, such as a bear or a worm?</td>","</tr>","<tr class=\"even\">","<td style=\"text-align: left;\">complex</td>","<td style=\"text-align: left;\">Does it have a complex flavor profile?</td>","</tr>","<tr class=\"odd\">","<td style=\"text-align: left;\">colorful</td>","<td style=\"text-align: left;\">Is it brightly colored or multicolored?</td>","</tr>","</tbody>","</table>","</div>","</div>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<p>Of course, our initial question is answered easily by simply looking at the data. Reese’s has appeared to corner the candy market, occupying 4 out of the top 10 candies, with their original Peanut Butter Cup securing the top spot. But what is it <em>about</em> those cups that make them so popular?</p>","<p>In our research, we aim to answer the question: What attributes are most directly correlated with a candy’s popularity (measured by win percentage), and how can we use them to create the most marketable candy possible? Based on a candy’s attributes, can we predict how popular a candy might be?</p>","<p>Hickey’s original research concludes that the presence of chocolate is the greatest predictor of a candy’s success, but the answer might not be that simple. After all, Hershey’s Milk Chocolate only placed 28th, below non-chocolates like Sour Patch Kids, Starburst, and Haribo Gold Bears. We posit that the greatest predictor of a candy’s success is not the presence of one <em>specific</em> flavor, but rather a collection of <em>complex</em> flavors, colors, and/or shapes. The cardinal sin of Halloween is to be boring, and we believe that our research will corroborate that.</p>","<p>Hickey’s research does not take these attributes into account, so some data wrangling was necessary in order to validate our hypothesis.</p>","<p>First, we removed the ‘One quarter’ and ‘One dime’ entries, as they aren’t candy and Hickey admits in the article that he included them as a joke. (Though interestingly they performed decently well in the bracket - a dime won 32% of its matchups and a quarter won 46% of the time.) Then we added four new columns relating to four specific features that we think will be correlated to a candy’s popularity - if a candy is sour, if it has an interesting shape, if it has a complex flavor profile, and if it’s a bright color. Bright colors and sour flavors were added because the data set itself seems to be biased towards chocolate candies - chocolate bars were given 6 layers of analysis, while fruit candies were only given the attribute ‘fruity’! A candy was labelled ‘complex’ if it contained two or more different flavor attributes.</p>","<p>We plan on using all of these attributes when building our prediction model. These binary variables on their own do not provide too much information, but the unique combinations of them for each candy may help us uncover what unique flavor profile and physical attributes are most appealing to the public.</p>","</section>","<section id=\"methodology\" class=\"level2\">","<h2 class=\"anchored\" data-anchor-id=\"methodology\">Methodology</h2>","<p>Our outcome variable is the candy’s popularity, shown in the data set as <code>winpercent</code> - how often it was selected as a preferred option as opposed to its randomly selected competitor. It is a numerical variable, and is a representation of the probability that a candy is preferable to the others, and thus its ‘popularity’. Because we are looking to understand how a candy’s attributes might affect its popularity, our key exploratory variables include the candy’s individual attributes - that is, all of the categorical columns of the dataset. Based on analysis of the correlation between attributes and popularity, we can then make predictions of a candy’s popularity based on its attributes.</p>","<p>Lastly, for our preliminary analysis, we will create graphs to figure out the relationship between features of a candy (chocolate content, complexity, and shape) and its win percent. We hypothesize that win percent has a positive correlation with chocolate content, complexity, interesting shapes, and colorfulness.</p>","<p>In order to present relevant summary statistics for the data, as well as run preliminary analysis of how different characteristics of a candy affects its win percent, we are using means and bar graphs to plot the relationship between a candy’s characteristics and its win percent. Firstly, the overall average win percent is calculated to provide a threshold to determine whether a candy scores better than the average win percent. The bar graph, then, shows the proportion of the candy’s win percent, according to the threshold, based on if it has the characteristic (1) or if it doesn’t (0). The mean win percent for each candy’s categories and whether or not they have the characteristics is also calculated.</p>","<div class=\"cell\">","<div class=\"cell-output-display\">","<p><img src=\"final_report_files/figure-html/unnamed-chunk-5-1.png\" class=\"img-fluid\" width=\"672\"></p>","</div>","</div>","<p>Hickey was on to something in his research - candies that contained chocolate had a win percent average of 60.92%, while candies that did not won on average 42.27% of the time.</p>","<div class=\"cell\">","<div class=\"cell-output-display\">","<p><img src=\"final_report_files/figure-html/unnamed-chunk-6-1.png\" class=\"img-fluid\" width=\"672\"></p>","</div>","</div>","<p>It appears that our initial hypothesis has some merit, as candies with a complex flavor profile had an average win percent of 59.69% - compared to simple candy’s 43.61% average win percentage, that’s a big leap!</p>","<div class=\"cell\">","<div class=\"cell-output-display\">","<p><img src=\"final_report_files/figure-html/unnamed-chunk-7-1.png\" class=\"img-fluid\" width=\"672\"></p>","</div>","</div>","<p>Curiously, there seems to be a negative association between a candy’s interesting visual attributes and its popularity. Candies in simple shapes have an average win percentage of 52.39%, while their funky-shaped competitors win 44.51% of the time.</p>","<div class=\"cell\">","<div class=\"cell-output-display\">","<p><img src=\"final_report_files/figure-html/unnamed-chunk-8-1.png\" class=\"img-fluid\" width=\"672\"></p>","</div>","</div>","<p>To corroborate the earlier point, colorful candies win their match-ups 46.18% of the time, and non-colorful candies win on average 55.8% of the time.</p>","<p>Perhaps candy manufacturers give visual appeal to candies that aren’t themselves very tasty?</p>","<p>From these graphs and the calculated means, we see that chocolate content and complexity are positively correlated with a candy’s win percent, with candies that contain chocolate holding the highest mean win percent. An interesting shape however, seems to have a negative correlation with a candy’s win percent if only the calculated mean was looked at, however from the graph it seems as though an interesting shape only marginally receives a lesser proportion of win percent that is greater than the average.</p>","<p>Colorful candies seem to have a higher proportion of lower than average win percent, and this is also backed up by the calculated means, which means that color negatively impacts a candy’s win percent. Upon further investigation, it is found that the sample size of interestingly shaped candies is very small and would not properly reflect in the calculated mean. Thus, both visualization and calculated means are important to corroborate the results seen from the summary statistics.</p>","<p>To analyze the correlation between a candy’s attributes and its popularity, we will be using a variety of regression models (decision tree, random forest, and GBM) to analyze the data. We will select the best model and use it to make our final predictions. The reason we are fitting multiple models is because of our small data set. These models are all compatible with regression, and vary in complexity and accuracy, with interpretability often being the trade-off. Because almost all of our predictors are binary, we want to use more complex models that may be able to interpret these rather uninformative variables in a way that will lead to higher accuracy. We don’t believe a linear regression model could perform this well. By using multiple models we hope to get the best performing machine possible. We hypothesize that win percent has a positive correlation with chocolate content, complexity, and interesting shapes.</p>","</section>","<section id=\"results\" class=\"level2\">","<h2 class=\"anchored\" data-anchor-id=\"results\">Results</h2>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<p>We choose to use Leave-One-Out Cross-Validation (LOOCV) instead of a traditional train-test split method for evaluating machine learning models due to the small size of our data set. With a small data set, a train-test split can result in a small sample size for training the model, leading to overfitting or underfitting depending on the number of observations and features in the data. LOOCV allows us to train the model on almost the entire data set, while still allowing for independent evaluation of the model’s performance on each data point. This approach provides a more accurate estimate of the model’s performance on new, unseen data, which is especially important when dealing with a small data set. Additionally, LOOCV eliminates the potential bias introduced by a random train-test split and provides a more reliable estimate of the model’s generalization performance. Overall, LOOCV is a suitable approach for evaluating machine learning models when dealing with small data sets, as it provides a more accurate and reliable estimate of model performance.</p>","<section id=\"random-forest\" class=\"level3\">","<h3 class=\"anchored\" data-anchor-id=\"random-forest\">Random Forest</h3>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<p>After performing cross-validation to find the best Random Forest Regressor model, an RF with a max depth of 10, a minimum number of samples required for each internal node for a split of 2, and the number of estimators to be 100 is the best for predicting candy popularity using the candy data set. The model achieves an MSE of 134.6 and an <span class=\"math inline\">\\(R^2\\)</span> score of 0.37. The Random Forest Regressor model uses an ensemble of decision trees to make predictions, which can capture nonlinear relationships and interactions between features that may not be captured by a linear model.</p>","</section>","<section id=\"decision-tree\" class=\"level3\">","<h3 class=\"anchored\" data-anchor-id=\"decision-tree\">Decision Tree</h3>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<p>For a Decision Tree Regressor model, it performs best when the max depth is 5, the minimum of samples needed to split an internal node is 10, and the minimum number of samples to be considered a leaf is 4. The model achieves an MSE of 142.21 and an <span class=\"math inline\">\\(R^2\\)</span> score of 0.34, which is lower than the performance of the Random Forest Regressor model on the same data set. The Decision Tree Regressor model is a simpler model than the Random Forest Regressor model and can be useful for interpreting the relationships between features and the target variable. However, in this case, the Random Forest Regressor model performs better.</p>","</section>","<section id=\"gradient-boosting-regressor\" class=\"level3\">","<h3 class=\"anchored\" data-anchor-id=\"gradient-boosting-regressor\">Gradient Boosting Regressor</h3>","<div class=\"cell\">","","</div>","<div class=\"cell\">","","</div>","<p>The best hyperparameters for the GBM model are to have a learning rate of 0.1, a maximum depth of 7, the square root of the number of features used to determine the best split, 1 samples minimum for each leaf, 5 samples minimum samples for a split of an internal node, and 200 estimators. The MSE is relatively high at 138.73 and the <span class=\"math inline\">\\(R^2\\)</span> score is 0.35.</p>","<p>In conclusion, the Random Forest Regressor model can best predict candy popularity using the candy data set. It accounts for about 37.37% of the variation in win percentage of a certain candy. The MSE is still relatively high, with an error of 134.6 on the entire model. This performs slightly better than the GBM, and much better than only using one decision tree.</p>","<div class=\"cell\">","<div class=\"cell-output-display\">","<style>#sk-container-id-1 {color: black;background-color: white;}#sk-container-id-1 pre{padding: 0;}#sk-container-id-1 div.sk-toggleable {background-color: white;}#sk-container-id-1 label.sk-toggleable__label {cursor: pointer;display: block;width: 100%;margin-bottom: 0;padding: 0.3em;box-sizing: border-box;text-align: center;}#sk-container-id-1 label.sk-toggleable__label-arrow:before {content: \"▸\";float: left;margin-right: 0.25em;color: #696969;}#sk-container-id-1 label.sk-toggleable__label-arrow:hover:before {color: black;}#sk-container-id-1 div.sk-estimator:hover label.sk-toggleable__label-arrow:before {color: black;}#sk-container-id-1 div.sk-toggleable__content {max-height: 0;max-width: 0;overflow: hidden;text-align: left;background-color: #f0f8ff;}#sk-container-id-1 div.sk-toggleable__content pre {margin: 0.2em;color: black;border-radius: 0.25em;background-color: #f0f8ff;}#sk-container-id-1 input.sk-toggleable__control:checked~div.sk-toggleable__content {max-height: 200px;max-width: 100%;overflow: auto;}#sk-container-id-1 input.sk-toggleable__control:checked~label.sk-toggleable__label-arrow:before {content: \"▾\";}#sk-container-id-1 div.sk-estimator input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-label input.sk-toggleable__control:checked~label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 input.sk-hidden--visually {border: 0;clip: rect(1px 1px 1px 1px);clip: rect(1px, 1px, 1px, 1px);height: 1px;margin: -1px;overflow: hidden;padding: 0;position: absolute;width: 1px;}#sk-container-id-1 div.sk-estimator {font-family: monospace;background-color: #f0f8ff;border: 1px dotted black;border-radius: 0.25em;box-sizing: border-box;margin-bottom: 0.5em;}#sk-container-id-1 div.sk-estimator:hover {background-color: #d4ebff;}#sk-container-id-1 div.sk-parallel-item::after {content: \"\";width: 100%;border-bottom: 1px solid gray;flex-grow: 1;}#sk-container-id-1 div.sk-label:hover label.sk-toggleable__label {background-color: #d4ebff;}#sk-container-id-1 div.sk-serial::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: 0;}#sk-container-id-1 div.sk-serial {display: flex;flex-direction: column;align-items: center;background-color: white;padding-right: 0.2em;padding-left: 0.2em;position: relative;}#sk-container-id-1 div.sk-item {position: relative;z-index: 1;}#sk-container-id-1 div.sk-parallel {display: flex;align-items: stretch;justify-content: center;background-color: white;position: relative;}#sk-container-id-1 div.sk-item::before, #sk-container-id-1 div.sk-parallel-item::before {content: \"\";position: absolute;border-left: 1px solid gray;box-sizing: border-box;top: 0;bottom: 0;left: 50%;z-index: -1;}#sk-container-id-1 div.sk-parallel-item {display: flex;flex-direction: column;z-index: 1;position: relative;background-color: white;}#sk-container-id-1 div.sk-parallel-item:first-child::after {align-self: flex-end;width: 50%;}#sk-container-id-1 div.sk-parallel-item:last-child::after {align-self: flex-start;width: 50%;}#sk-container-id-1 div.sk-parallel-item:only-child::after {width: 0;}#sk-container-id-1 div.sk-dashed-wrapped {border: 1px dashed gray;margin: 0 0.4em 0.5em 0.4em;box-sizing: border-box;padding-bottom: 0.4em;background-color: white;}#sk-container-id-1 div.sk-label label {font-family: monospace;font-weight: bold;display: inline-block;line-height: 1.2em;}#sk-container-id-1 div.sk-label-container {text-align: center;}#sk-container-id-1 div.sk-container {/* jupyter's `normalize.less` sets `[hidden] { display: none; }` but bootstrap.min.css set `[hidden] { display: none !important; }` so we also need the `!important` here to be able to override the default hidden behavior on the sphinx rendered scikit-learn.org. See: https://github.com/scikit-learn/scikit-learn/issues/21755 */display: inline-block !important;position: relative;}#sk-container-id-1 div.sk-text-repr-fallback {display: none;}</style><div id=\"sk-container-id-1\" class=\"sk-top-container\"><div class=\"sk-text-repr-fallback\"><pre>Pipeline(steps=[('preprocessor',","                 ColumnTransformer(remainder='passthrough',","                                   transformers=[('standardscaler',","                                                  StandardScaler(),","                                                  [9, 10])])),","                ('rf', RandomForestRegressor(max_depth=10))])</pre><b>In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook. <br>On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.</b></div><div class=\"sk-container\" hidden=\"\"><div class=\"sk-item sk-dashed-wrapped\"><div class=\"sk-label-container\"><div class=\"sk-label sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-1\" type=\"checkbox\"><label for=\"sk-estimator-id-1\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">Pipeline</label><div class=\"sk-toggleable__content\"><pre>Pipeline(steps=[('preprocessor',","                 ColumnTransformer(remainder='passthrough',","                                   transformers=[('standardscaler',","                                                  StandardScaler(),","                                                  [9, 10])])),","                ('rf', RandomForestRegressor(max_depth=10))])</pre></div></div></div><div class=\"sk-serial\"><div class=\"sk-item sk-dashed-wrapped\"><div class=\"sk-label-container\"><div class=\"sk-label sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-2\" type=\"checkbox\"><label for=\"sk-estimator-id-2\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">preprocessor: ColumnTransformer</label><div class=\"sk-toggleable__content\"><pre>ColumnTransformer(remainder='passthrough',","                  transformers=[('standardscaler', StandardScaler(), [9, 10])])</pre></div></div></div><div class=\"sk-parallel\"><div class=\"sk-parallel-item\"><div class=\"sk-item\"><div class=\"sk-label-container\"><div class=\"sk-label sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-3\" type=\"checkbox\"><label for=\"sk-estimator-id-3\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">standardscaler</label><div class=\"sk-toggleable__content\"><pre>[9, 10]</pre></div></div></div><div class=\"sk-serial\"><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-4\" type=\"checkbox\"><label for=\"sk-estimator-id-4\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">StandardScaler</label><div class=\"sk-toggleable__content\"><pre>StandardScaler()</pre></div></div></div></div></div></div><div class=\"sk-parallel-item\"><div class=\"sk-item\"><div class=\"sk-label-container\"><div class=\"sk-label sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-5\" type=\"checkbox\"><label for=\"sk-estimator-id-5\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">remainder</label><div class=\"sk-toggleable__content\"><pre>['chocolate', 'fruity', 'caramel', 'peanutyalmondy', 'nougat', 'crispedricewafer', 'hard', 'bar', 'pluribus', 'shaped', 'sour', 'complex', 'colorful']</pre></div></div></div><div class=\"sk-serial\"><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-6\" type=\"checkbox\"><label for=\"sk-estimator-id-6\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">passthrough</label><div class=\"sk-toggleable__content\"><pre>passthrough</pre></div></div></div></div></div></div></div></div><div class=\"sk-item\"><div class=\"sk-estimator sk-toggleable\"><input class=\"sk-toggleable__control sk-hidden--visually\" id=\"sk-estimator-id-7\" type=\"checkbox\"><label for=\"sk-estimator-id-7\" class=\"sk-toggleable__label sk-toggleable__label-arrow\">RandomForestRegressor</label><div class=\"sk-toggleable__content\"><pre>RandomForestRegressor(max_depth=10)</pre></div></div></div></div></div></div></div>","</div>","</div>","<p>The Random Forest Regressor model’s feature importance analysis shows that chocolate is the most important feature, with a weight of 0.376, followed by colorful and complex attributes with weights of 0.150 and 0.171, respectively. Other important features include fruity, caramel, peanutyalmondy, nougat, and sour. Pricepercent has the lowest feature importance weight, indicating that it has the least impact on candy popularity. These results suggest that a candy’s taste and appearance are more important than its price in determining its popularity.</p>","<div class=\"cell\">","<div class=\"cell-output cell-output-stdout\">","<pre><code>Winning Percentage with Only One Attribute:</code></pre>","</div>","<div class=\"cell-output cell-output-stdout\">","<pre><code>chocolate: 50.02","colorful: 37.43","sugarpercent: 36.79","complex: 36.38","bar: 35.58","shaped: 35.41","caramel: 35.15","nougat: 34.29","hard: 34.09","sour: 34.09","fruity: 33.80","peanutyalmondy: 33.60","crispedricewafer: 33.59","pluribus: 33.16","pricepercent: 29.67</code></pre>","</div>","</div>","<p>The Random Forest Regressor model was used to predict the popularity of different attributes of candy. The predicted popularity values for each attribute were then sorted in descending order. The attribute with the highest predicted popularity is chocolate with a score of 50.02, followed by a sugar percentile of 1 (the most sugary) with an expected winning percentage of 36.79 and colorful with a predicted winning percentage of 37.43 These results suggest that chocolate and high sugar content are strong predictors of candy popularity. A price percentile of 1 (most expensive) of a candy is predicted to be the least important attribute in predicting candy popularity. These results can be useful for candy manufacturers and marketers to understand which attributes of candy are most likely to be popular among consumers.</p>","</section>","<section id=\"feature-importances\" class=\"level3\">","<h3 class=\"anchored\" data-anchor-id=\"feature-importances\">Feature Importances</h3>","<div class=\"cell\">","<div class=\"cell-output-display\">","<p><img src=\"final_report_files/figure-html/unnamed-chunk-20-1.png\" class=\"img-fluid\" width=\"576\"></p>","</div>","</div>","<p>Based on the Random Forest Regressor model, the most important attribute for predicting candy popularity is <code>caramel</code>, followed by <code>chocolate</code> and <code>fruity</code>. The other attributes may also play a role in candy popularity, but to a lesser extent. The least important attribute is <code>sour</code>. It’s important to note that these results are specific to the data set and may not generalize to other populations or contexts.</p>","</section>","</section>","<section id=\"discussion\" class=\"level2\">","<h2 class=\"anchored\" data-anchor-id=\"discussion\">Discussion</h2>","<p>After attempting to fit multiple regression prediction models, we found that it is hard for machines to predict how popular a certain candy will be based on their flavor profile, visual and tactile presentation, and price. Out of the decision tree, random forest, and GBM models, the Random Forest Regressor model performed the best, with the highest <span class=\"math inline\">\\(R^2\\)</span> value of 0.37 and smallest MSE of 134.6. However, this model still only accounts for about a third of the variation in win percentage. We hypothesized that chocolate, complex flavors, and an interesting shape may all positively contribute to predicting a candy’s winning percentage. Chocolate is the second most important feature in predicting winning percentage, with a feature importance value of 0.3818; caramel has the highest feature importance of . Complexity of the candy is the fourth most important, with a feature importance of 0.1626. Shape does not seem to contribute much, with a feature importance of 0.0157. Higher values of feature importance indicates the degree to which that predictor contributes to the final model. Feature importance values range from 0 to 1, but none of them having an importance of even 0.4 reflects the limitations of our data and difficulty predicting win percentage from the data set.</p>","<p>To test our model, we defined candies with only one of 15 attributes being marked as present. Then, we predicted the winning percentage using our optimal Random Forest Regressor model. The results reveal that chocolate as the only attribute has the highest winning percentage of 50.02. It’s hard to interpret these estimates in context (in regards to the predicted winning percentage with only that attribute present). For example, a candy cannot have an interesting shape with no other of the listed attributes (it would have no flavor). Under a similar interpretation, if a candy has a complex flavor profile but none of the individual flavors, then what does this complex flavor consist of? Our model predicts candies with a price percentile of 1 (most expensive) to have the lowest winning percentage, but this theoretical candy has no flavor or visual attributes. There is inherent interaction between these variables, which our predictions do not account for.</p>","<p>Because our data set is relatively small, we opted for a LOOCV (leave one out cross-validation) method to find the optimal model. This is a more computationally expensive algorithm but gives us more leverage with our small amount of data. The training data, with its inherent limitation of being rather small, limits the validity of our model. While we did use the LOOCV method to maximize each observation, 83 observations is still a very small amount to fit a model to. Something else that may limit the predictions for new data we can make is that the categories added to the original data set are mostly arbitrary. Analyst Sarah Kessler hand-picked candies that fit the criteria for each category out of the data set, imparting a not insignificant amount of human error. Perhaps a few different candies could have been categorized as colorful or interesting by a different human analyst, and that could have contributed to different scores in the <code>colorful</code> and <code>shaped</code> columns.</p>","<p>If we were able to start over with the project, we probably would try to find a new data set. There are not many observations in this data set, and while we tried sourcing the original, raw data, it proved unsuccessful. Having this raw data may have lead to a much more interesting analysis. If we were able to conduct the same survey as Hickey, we would ask about other demographic information like age, gender, location etc. Perhaps there’s a stratified difference depending on who the candy consumer is (ex. children may like colorful, interestingly shaped candy, while adults may be more about the complexity of the flavor profile). Including factors other than the candy’s attributes would also give us a richer data set with variables that aren’t binary indicators. Like Hickey, we would probably deploy it online and try to gather a large, randomized sample size. The resulting data would also give us the results of each comparison, rather than the overall percentage of matchups each candy won. So, not only could we predict the absolute win percentage, but perhaps we could predict if a given candy would fall in the top 5 or bottom 5 (a question of classification). Only having 83 observations is an inherent limitation to building a model and performing predictions.</p>","</section>","<section id=\"citation\" class=\"level2\">","<h2 class=\"anchored\" data-anchor-id=\"citation\">Citation</h2>","<p>Hickey, W. (2017, October 27). <em>The ultimate halloween candy power ranking.</em> FiveThirtyEight. Retrieved April 16, 2023, from https://fivethirtyeight.com/videos/the-ultimate-halloween-candy-power-ranking/</p>","</section>","","</main>","<!-- /main column -->","<script id=\"quarto-html-after-body\" type=\"application/javascript\">","window.document.addEventListener(\"DOMContentLoaded\", function (event) {","  const toggleBodyColorMode = (bsSheetEl) => {","    const mode = bsSheetEl.getAttribute(\"data-mode\");","    const bodyEl = window.document.querySelector(\"body\");","    if (mode === \"dark\") {","      bodyEl.classList.add(\"quarto-dark\");","      bodyEl.classList.remove(\"quarto-light\");","    } else {","      bodyEl.classList.add(\"quarto-light\");","      bodyEl.classList.remove(\"quarto-dark\");","    }","  }","  const toggleBodyColorPrimary = () => {","    const bsSheetEl = window.document.querySelector(\"link#quarto-bootstrap\");","    if (bsSheetEl) {","      toggleBodyColorMode(bsSheetEl);","    }","  }","  toggleBodyColorPrimary();  ","  const icon = \"\";","  const anchorJS = new window.AnchorJS();","  anchorJS.options = {","    placement: 'right',","    icon: icon","  };","  anchorJS.add('.anchored');","  const clipboard = new window.ClipboardJS('.code-copy-button', {","    target: function(trigger) {","      return trigger.previousElementSibling;","    }","  });","  clipboard.on('success', function(e) {","    // button target","    const button = e.trigger;","    // don't keep focus","    button.blur();","    // flash \"checked\"","    button.classList.add('code-copy-button-checked');","    var currentTitle = button.getAttribute(\"title\");","    button.setAttribute(\"title\", \"Copied!\");","    let tooltip;","    if (window.bootstrap) {","      button.setAttribute(\"data-bs-toggle\", \"tooltip\");","      button.setAttribute(\"data-bs-placement\", \"left\");","      button.setAttribute(\"data-bs-title\", \"Copied!\");","      tooltip = new bootstrap.Tooltip(button, ","        { trigger: \"manual\", ","          customClass: \"code-copy-button-tooltip\",","          offset: [0, -8]});","      tooltip.show();    ","    }","    setTimeout(function() {","      if (tooltip) {","        tooltip.hide();","        button.removeAttribute(\"data-bs-title\");","        button.removeAttribute(\"data-bs-toggle\");","        button.removeAttribute(\"data-bs-placement\");","      }","      button.setAttribute(\"title\", currentTitle);","      button.classList.remove('code-copy-button-checked');","    }, 1000);","    // clear code selection","    e.clearSelection();","  });","  function tippyHover(el, contentFn) {","    const config = {","      allowHTML: true,","      content: contentFn,","      maxWidth: 500,","      delay: 100,","      arrow: false,","      appendTo: function(el) {","          return el.parentElement;","      },","      interactive: true,","      interactiveBorder: 10,","      theme: 'quarto',","      placement: 'bottom-start'","    };","    window.tippy(el, config); ","  }","  const noterefs = window.document.querySelectorAll('a[role=\"doc-noteref\"]');","  for (var i=0; i<noterefs.length; i++) {","    const ref = noterefs[i];","    tippyHover(ref, function() {","      // use id or data attribute instead here","      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');","      try { href = new URL(href).hash; } catch {}","      const id = href.replace(/^#\\/?/, \"\");","      const note = window.document.getElementById(id);","      return note.innerHTML;","    });","  }","  const findCites = (el) => {","    const parentEl = el.parentElement;","    if (parentEl) {","      const cites = parentEl.dataset.cites;","      if (cites) {","        return {","          el,","          cites: cites.split(' ')","        };","      } else {","        return findCites(el.parentElement)","      }","    } else {","      return undefined;","    }","  };","  var bibliorefs = window.document.querySelectorAll('a[role=\"doc-biblioref\"]');","  for (var i=0; i<bibliorefs.length; i++) {","    const ref = bibliorefs[i];","    const citeInfo = findCites(ref);","    if (citeInfo) {","      tippyHover(citeInfo.el, function() {","        var popup = window.document.createElement('div');","        citeInfo.cites.forEach(function(cite) {","          var citeDiv = window.document.createElement('div');","          citeDiv.classList.add('hanging-indent');","          citeDiv.classList.add('csl-entry');","          var biblioDiv = window.document.getElementById('ref-' + cite);","          if (biblioDiv) {","            citeDiv.innerHTML = biblioDiv.innerHTML;","          }","          popup.appendChild(citeDiv);","        });","        return popup.innerHTML;","      });","    }","  }","});","</script>","</div> <!-- /content -->","","","","</body></html>"],"stylingDirectives":[[{"start":0,"end":15,"cssClass":"pl-c1"},{"start":14,"end":15,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":41,"cssClass":"pl-s"},{"start":43,"end":47,"cssClass":"pl-c1"},{"start":49,"end":51,"cssClass":"pl-s"},{"start":53,"end":61,"cssClass":"pl-c1"},{"start":63,"end":65,"cssClass":"pl-s"},{"start":66,"end":67,"cssClass":"pl-kos"},{"start":67,"end":68,"cssClass":"pl-kos"},{"start":68,"end":72,"cssClass":"pl-ent"},{"start":72,"end":73,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":13,"cssClass":"pl-c1"},{"start":15,"end":20,"cssClass":"pl-s"},{"start":21,"end":22,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":21,"cssClass":"pl-s"},{"start":23,"end":30,"cssClass":"pl-c1"},{"start":32,"end":46,"cssClass":"pl-s"},{"start":47,"end":48,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":20,"cssClass":"pl-s"},{"start":22,"end":29,"cssClass":"pl-c1"},{"start":31,"end":87,"cssClass":"pl-s"},{"start":88,"end":89,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":18,"cssClass":"pl-s"},{"start":20,"end":27,"cssClass":"pl-c1"},{"start":29,"end":36,"cssClass":"pl-s"},{"start":37,"end":38,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":24,"cssClass":"pl-s"},{"start":26,"end":33,"cssClass":"pl-c1"},{"start":35,"end":45,"cssClass":"pl-s"},{"start":46,"end":47,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":87,"end":89,"cssClass":"pl-kos"},{"start":89,"end":94,"cssClass":"pl-ent"},{"start":94,"end":95,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":0,"end":4,"cssClass":"pl-ent"},{"start":5,"end":16,"cssClass":"pl-c1"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":4,"cssClass":"pl-ent"},{"start":5,"end":14,"cssClass":"pl-c1"},{"start":15,"end":27,"cssClass":"pl-c1"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":0,"end":3,"cssClass":"pl-ent"},{"start":4,"end":11,"cssClass":"pl-c1"},{"start":12,"end":19,"cssClass":"pl-c1"},{"start":19,"end":20,"cssClass":"pl-kos"},{"start":27,"end":30,"cssClass":"pl-c1"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":32,"end":35,"cssClass":"pl-en"},{"start":36,"end":39,"cssClass":"pl-c1"},{"start":37,"end":39,"cssClass":"pl-smi"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":41,"end":46,"cssClass":"pl-c1"},{"start":44,"end":46,"cssClass":"pl-smi"}],[{"start":0,"end":3,"cssClass":"pl-ent"},{"start":4,"end":10,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-c1"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":23,"end":33,"cssClass":"pl-c1"},{"start":33,"end":34,"cssClass":"pl-kos"}],[{"start":0,"end":3,"cssClass":"pl-ent"},{"start":4,"end":18,"cssClass":"pl-c1"},{"start":19,"end":30,"cssClass":"pl-c1"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":32,"end":37,"cssClass":"pl-c1"},{"start":35,"end":37,"cssClass":"pl-smi"},{"start":39,"end":50,"cssClass":"pl-c1"},{"start":50,"end":51,"cssClass":"pl-kos"},{"start":52,"end":58,"cssClass":"pl-c1"},{"start":56,"end":58,"cssClass":"pl-smi"}],[{"start":0,"end":2,"cssClass":"pl-ent"},{"start":3,"end":12,"cssClass":"pl-c1"},{"start":13,"end":23,"cssClass":"pl-c1"},{"start":23,"end":24,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-ent"},{"start":3,"end":12,"cssClass":"pl-c1"},{"start":13,"end":15,"cssClass":"pl-ent"},{"start":16,"end":21,"cssClass":"pl-ent"},{"start":22,"end":26,"cssClass":"pl-c1"},{"start":26,"end":27,"cssClass":"pl-c1"},{"start":27,"end":37,"cssClass":"pl-s"}],[{"start":2,"end":7,"cssClass":"pl-c1"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":12,"end":14,"cssClass":"pl-smi"}],[{"start":2,"end":8,"cssClass":"pl-c1"},{"start":8,"end":9,"cssClass":"pl-kos"},{"start":10,"end":11,"cssClass":"pl-c1"},{"start":12,"end":17,"cssClass":"pl-c1"},{"start":15,"end":17,"cssClass":"pl-smi"},{"start":18,"end":23,"cssClass":"pl-c1"},{"start":21,"end":23,"cssClass":"pl-smi"},{"start":24,"end":30,"cssClass":"pl-c1"},{"start":28,"end":30,"cssClass":"pl-smi"}],[{"start":2,"end":16,"cssClass":"pl-c1"},{"start":16,"end":17,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":63,"cssClass":"pl-s"},{"start":64,"end":65,"cssClass":"pl-kos"},{"start":65,"end":67,"cssClass":"pl-kos"},{"start":67,"end":73,"cssClass":"pl-ent"},{"start":73,"end":74,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":58,"cssClass":"pl-s"},{"start":59,"end":60,"cssClass":"pl-kos"},{"start":60,"end":62,"cssClass":"pl-kos"},{"start":62,"end":68,"cssClass":"pl-ent"},{"start":68,"end":69,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":62,"cssClass":"pl-s"},{"start":63,"end":64,"cssClass":"pl-kos"},{"start":64,"end":66,"cssClass":"pl-kos"},{"start":66,"end":72,"cssClass":"pl-ent"},{"start":72,"end":73,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":65,"cssClass":"pl-s"},{"start":66,"end":67,"cssClass":"pl-kos"},{"start":67,"end":69,"cssClass":"pl-kos"},{"start":69,"end":75,"cssClass":"pl-ent"},{"start":75,"end":76,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":62,"cssClass":"pl-s"},{"start":63,"end":64,"cssClass":"pl-kos"},{"start":64,"end":66,"cssClass":"pl-kos"},{"start":66,"end":72,"cssClass":"pl-ent"},{"start":72,"end":73,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":57,"cssClass":"pl-s"},{"start":59,"end":62,"cssClass":"pl-c1"},{"start":64,"end":74,"cssClass":"pl-s"},{"start":75,"end":76,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":78,"cssClass":"pl-s"},{"start":80,"end":83,"cssClass":"pl-c1"},{"start":85,"end":95,"cssClass":"pl-s"},{"start":97,"end":99,"cssClass":"pl-c1"},{"start":101,"end":132,"cssClass":"pl-s"},{"start":133,"end":134,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":63,"cssClass":"pl-s"},{"start":64,"end":65,"cssClass":"pl-kos"},{"start":65,"end":67,"cssClass":"pl-kos"},{"start":67,"end":73,"cssClass":"pl-ent"},{"start":73,"end":74,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":65,"cssClass":"pl-s"},{"start":67,"end":70,"cssClass":"pl-c1"},{"start":72,"end":82,"cssClass":"pl-s"},{"start":83,"end":84,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":10,"cssClass":"pl-c1"},{"start":12,"end":63,"cssClass":"pl-s"},{"start":65,"end":68,"cssClass":"pl-c1"},{"start":70,"end":80,"cssClass":"pl-s"},{"start":82,"end":84,"cssClass":"pl-c1"},{"start":86,"end":102,"cssClass":"pl-s"},{"start":104,"end":113,"cssClass":"pl-c1"},{"start":115,"end":120,"cssClass":"pl-s"},{"start":121,"end":122,"cssClass":"pl-kos"}],[],[{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":9,"cssClass":"pl-ent"},{"start":10,"end":13,"cssClass":"pl-c1"},{"start":15,"end":75,"cssClass":"pl-s"},{"start":77,"end":81,"cssClass":"pl-c1"},{"start":83,"end":98,"cssClass":"pl-s"},{"start":99,"end":100,"cssClass":"pl-kos"},{"start":100,"end":102,"cssClass":"pl-kos"},{"start":102,"end":108,"cssClass":"pl-ent"},{"start":108,"end":109,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":24,"cssClass":"pl-s"},{"start":25,"end":26,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":7,"cssClass":"pl-c1"},{"start":9,"end":23,"cssClass":"pl-s"},{"start":25,"end":30,"cssClass":"pl-c1"},{"start":32,"end":83,"cssClass":"pl-s"},{"start":84,"end":85,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":5,"cssClass":"pl-ent"},{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":20,"cssClass":"pl-s"},{"start":22,"end":24,"cssClass":"pl-c1"},{"start":26,"end":49,"cssClass":"pl-s"},{"start":50,"end":51,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":10,"cssClass":"pl-c1"},{"start":12,"end":30,"cssClass":"pl-s"},{"start":32,"end":37,"cssClass":"pl-c1"},{"start":39,"end":65,"cssClass":"pl-s"},{"start":66,"end":67,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":24,"cssClass":"pl-s"},{"start":25,"end":26,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":98,"end":100,"cssClass":"pl-kos"},{"start":100,"end":102,"cssClass":"pl-ent"},{"start":102,"end":103,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[],[],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":29,"cssClass":"pl-s"},{"start":30,"end":31,"cssClass":"pl-kos"}],[],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":8,"end":9,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":16,"end":41,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":49,"end":51,"cssClass":"pl-kos"},{"start":51,"end":54,"cssClass":"pl-ent"},{"start":54,"end":55,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":16,"end":42,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":13,"end":14,"cssClass":"pl-kos"},{"start":14,"end":15,"cssClass":"pl-ent"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":24,"end":26,"cssClass":"pl-kos"},{"start":26,"end":27,"cssClass":"pl-ent"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":10,"end":12,"cssClass":"pl-kos"},{"start":12,"end":15,"cssClass":"pl-ent"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":2,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":8,"end":9,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":16,"end":41,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":52,"end":54,"cssClass":"pl-kos"},{"start":54,"end":57,"cssClass":"pl-ent"},{"start":57,"end":58,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":8,"cssClass":"pl-ent"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":16,"end":42,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":8,"cssClass":"pl-ent"},{"start":9,"end":14,"cssClass":"pl-c1"},{"start":16,"end":20,"cssClass":"pl-s"},{"start":21,"end":22,"cssClass":"pl-kos"},{"start":33,"end":35,"cssClass":"pl-kos"},{"start":35,"end":36,"cssClass":"pl-ent"},{"start":36,"end":37,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-kos"},{"start":6,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":2,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[],[],[{"start":2,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":8,"cssClass":"pl-ent"},{"start":8,"end":9,"cssClass":"pl-kos"}],[],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":34,"cssClass":"pl-s"},{"start":36,"end":41,"cssClass":"pl-c1"},{"start":43,"end":49,"cssClass":"pl-s"},{"start":50,"end":51,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":58,"cssClass":"pl-s"},{"start":59,"end":60,"cssClass":"pl-kos"},{"start":81,"end":83,"cssClass":"pl-kos"},{"start":83,"end":85,"cssClass":"pl-ent"},{"start":85,"end":86,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":363,"end":365,"cssClass":"pl-kos"},{"start":365,"end":366,"cssClass":"pl-ent"},{"start":366,"end":367,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":652,"end":654,"cssClass":"pl-kos"},{"start":654,"end":655,"cssClass":"pl-ent"},{"start":655,"end":656,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":538,"end":539,"cssClass":"pl-kos"},{"start":539,"end":541,"cssClass":"pl-ent"},{"start":541,"end":542,"cssClass":"pl-kos"},{"start":547,"end":549,"cssClass":"pl-kos"},{"start":549,"end":551,"cssClass":"pl-ent"},{"start":551,"end":552,"cssClass":"pl-kos"},{"start":586,"end":587,"cssClass":"pl-kos"},{"start":587,"end":589,"cssClass":"pl-ent"},{"start":589,"end":590,"cssClass":"pl-kos"},{"start":815,"end":817,"cssClass":"pl-kos"},{"start":817,"end":819,"cssClass":"pl-ent"},{"start":819,"end":820,"cssClass":"pl-kos"},{"start":820,"end":822,"cssClass":"pl-kos"},{"start":822,"end":823,"cssClass":"pl-ent"},{"start":823,"end":824,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":440,"end":442,"cssClass":"pl-kos"},{"start":442,"end":443,"cssClass":"pl-ent"},{"start":443,"end":444,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":7,"end":12,"cssClass":"pl-c1"},{"start":14,"end":42,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":8,"end":9,"cssClass":"pl-kos"},{"start":18,"end":20,"cssClass":"pl-kos"},{"start":20,"end":27,"cssClass":"pl-ent"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":17,"cssClass":"pl-s"},{"start":18,"end":19,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-kos"},{"start":40,"end":42,"cssClass":"pl-ent"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":41,"end":43,"cssClass":"pl-kos"},{"start":43,"end":45,"cssClass":"pl-ent"},{"start":45,"end":46,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":44,"end":46,"cssClass":"pl-kos"},{"start":46,"end":48,"cssClass":"pl-ent"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":51,"end":53,"cssClass":"pl-kos"},{"start":53,"end":55,"cssClass":"pl-ent"},{"start":55,"end":56,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":39,"end":41,"cssClass":"pl-kos"},{"start":41,"end":43,"cssClass":"pl-ent"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":56,"end":58,"cssClass":"pl-kos"},{"start":58,"end":60,"cssClass":"pl-ent"},{"start":60,"end":61,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-ent"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":51,"end":53,"cssClass":"pl-kos"},{"start":53,"end":55,"cssClass":"pl-ent"},{"start":55,"end":56,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":37,"end":39,"cssClass":"pl-kos"},{"start":39,"end":41,"cssClass":"pl-ent"},{"start":41,"end":42,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":54,"end":56,"cssClass":"pl-kos"},{"start":56,"end":58,"cssClass":"pl-ent"},{"start":58,"end":59,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":44,"end":46,"cssClass":"pl-kos"},{"start":46,"end":48,"cssClass":"pl-ent"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":70,"end":72,"cssClass":"pl-kos"},{"start":72,"end":74,"cssClass":"pl-ent"},{"start":74,"end":75,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-ent"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":53,"end":55,"cssClass":"pl-kos"},{"start":55,"end":57,"cssClass":"pl-ent"},{"start":57,"end":58,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":46,"end":48,"cssClass":"pl-kos"},{"start":48,"end":50,"cssClass":"pl-ent"},{"start":50,"end":51,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":94,"end":96,"cssClass":"pl-kos"},{"start":96,"end":98,"cssClass":"pl-ent"},{"start":98,"end":99,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":34,"end":36,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-ent"},{"start":38,"end":39,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":49,"end":51,"cssClass":"pl-kos"},{"start":51,"end":53,"cssClass":"pl-ent"},{"start":53,"end":54,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":33,"end":35,"cssClass":"pl-kos"},{"start":35,"end":37,"cssClass":"pl-ent"},{"start":37,"end":38,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":48,"end":50,"cssClass":"pl-kos"},{"start":50,"end":52,"cssClass":"pl-ent"},{"start":52,"end":53,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-kos"},{"start":40,"end":42,"cssClass":"pl-ent"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":89,"end":91,"cssClass":"pl-kos"},{"start":91,"end":93,"cssClass":"pl-ent"},{"start":93,"end":94,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":42,"end":44,"cssClass":"pl-kos"},{"start":44,"end":46,"cssClass":"pl-ent"},{"start":46,"end":47,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":92,"end":94,"cssClass":"pl-kos"},{"start":94,"end":96,"cssClass":"pl-ent"},{"start":96,"end":97,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":42,"end":44,"cssClass":"pl-kos"},{"start":44,"end":46,"cssClass":"pl-ent"},{"start":46,"end":47,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":88,"end":90,"cssClass":"pl-kos"},{"start":90,"end":92,"cssClass":"pl-ent"},{"start":92,"end":93,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":40,"end":42,"cssClass":"pl-kos"},{"start":42,"end":44,"cssClass":"pl-ent"},{"start":44,"end":45,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":87,"end":89,"cssClass":"pl-kos"},{"start":89,"end":91,"cssClass":"pl-ent"},{"start":91,"end":92,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":34,"end":36,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-ent"},{"start":38,"end":39,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":41,"end":43,"cssClass":"pl-kos"},{"start":43,"end":45,"cssClass":"pl-ent"},{"start":45,"end":46,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-ent"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":83,"end":85,"cssClass":"pl-kos"},{"start":85,"end":87,"cssClass":"pl-ent"},{"start":87,"end":88,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":15,"cssClass":"pl-s"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":37,"end":39,"cssClass":"pl-kos"},{"start":39,"end":41,"cssClass":"pl-ent"},{"start":41,"end":42,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":68,"end":70,"cssClass":"pl-kos"},{"start":70,"end":72,"cssClass":"pl-ent"},{"start":72,"end":73,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":14,"cssClass":"pl-s"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":38,"end":40,"cssClass":"pl-kos"},{"start":40,"end":42,"cssClass":"pl-ent"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":28,"cssClass":"pl-s"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":69,"end":71,"cssClass":"pl-kos"},{"start":71,"end":73,"cssClass":"pl-ent"},{"start":73,"end":74,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":7,"cssClass":"pl-ent"},{"start":7,"end":8,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":249,"end":250,"cssClass":"pl-kos"},{"start":250,"end":252,"cssClass":"pl-ent"},{"start":252,"end":253,"cssClass":"pl-kos"},{"start":258,"end":260,"cssClass":"pl-kos"},{"start":260,"end":262,"cssClass":"pl-ent"},{"start":262,"end":263,"cssClass":"pl-kos"},{"start":301,"end":303,"cssClass":"pl-kos"},{"start":303,"end":304,"cssClass":"pl-ent"},{"start":304,"end":305,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":297,"end":299,"cssClass":"pl-kos"},{"start":299,"end":300,"cssClass":"pl-ent"},{"start":300,"end":301,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":376,"end":377,"cssClass":"pl-kos"},{"start":377,"end":379,"cssClass":"pl-ent"},{"start":379,"end":380,"cssClass":"pl-kos"},{"start":388,"end":390,"cssClass":"pl-kos"},{"start":390,"end":392,"cssClass":"pl-ent"},{"start":392,"end":393,"cssClass":"pl-kos"},{"start":429,"end":430,"cssClass":"pl-kos"},{"start":430,"end":432,"cssClass":"pl-ent"},{"start":432,"end":433,"cssClass":"pl-kos"},{"start":440,"end":442,"cssClass":"pl-kos"},{"start":442,"end":444,"cssClass":"pl-ent"},{"start":444,"end":445,"cssClass":"pl-kos"},{"start":580,"end":582,"cssClass":"pl-kos"},{"start":582,"end":583,"cssClass":"pl-ent"},{"start":583,"end":584,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":139,"end":141,"cssClass":"pl-kos"},{"start":141,"end":142,"cssClass":"pl-ent"},{"start":142,"end":143,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":838,"end":840,"cssClass":"pl-kos"},{"start":840,"end":841,"cssClass":"pl-ent"},{"start":841,"end":842,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":308,"end":310,"cssClass":"pl-kos"},{"start":310,"end":311,"cssClass":"pl-ent"},{"start":311,"end":312,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":24,"cssClass":"pl-s"},{"start":26,"end":31,"cssClass":"pl-c1"},{"start":33,"end":39,"cssClass":"pl-s"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":48,"cssClass":"pl-s"},{"start":49,"end":50,"cssClass":"pl-kos"},{"start":61,"end":63,"cssClass":"pl-kos"},{"start":63,"end":65,"cssClass":"pl-ent"},{"start":65,"end":66,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":76,"end":77,"cssClass":"pl-kos"},{"start":77,"end":81,"cssClass":"pl-ent"},{"start":81,"end":82,"cssClass":"pl-kos"},{"start":92,"end":94,"cssClass":"pl-kos"},{"start":94,"end":98,"cssClass":"pl-ent"},{"start":98,"end":99,"cssClass":"pl-kos"},{"start":708,"end":710,"cssClass":"pl-kos"},{"start":710,"end":711,"cssClass":"pl-ent"},{"start":711,"end":712,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":318,"end":320,"cssClass":"pl-kos"},{"start":320,"end":321,"cssClass":"pl-ent"},{"start":321,"end":322,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":714,"end":716,"cssClass":"pl-kos"},{"start":716,"end":717,"cssClass":"pl-ent"},{"start":717,"end":718,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":65,"cssClass":"pl-s"},{"start":67,"end":72,"cssClass":"pl-c1"},{"start":74,"end":83,"cssClass":"pl-s"},{"start":85,"end":90,"cssClass":"pl-c1"},{"start":92,"end":95,"cssClass":"pl-s"},{"start":96,"end":97,"cssClass":"pl-kos"},{"start":97,"end":99,"cssClass":"pl-kos"},{"start":99,"end":100,"cssClass":"pl-ent"},{"start":100,"end":101,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":179,"end":181,"cssClass":"pl-kos"},{"start":181,"end":182,"cssClass":"pl-ent"},{"start":182,"end":183,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":65,"cssClass":"pl-s"},{"start":67,"end":72,"cssClass":"pl-c1"},{"start":74,"end":83,"cssClass":"pl-s"},{"start":85,"end":90,"cssClass":"pl-c1"},{"start":92,"end":95,"cssClass":"pl-s"},{"start":96,"end":97,"cssClass":"pl-kos"},{"start":97,"end":99,"cssClass":"pl-kos"},{"start":99,"end":100,"cssClass":"pl-ent"},{"start":100,"end":101,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":214,"end":216,"cssClass":"pl-kos"},{"start":216,"end":217,"cssClass":"pl-ent"},{"start":217,"end":218,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":65,"cssClass":"pl-s"},{"start":67,"end":72,"cssClass":"pl-c1"},{"start":74,"end":83,"cssClass":"pl-s"},{"start":85,"end":90,"cssClass":"pl-c1"},{"start":92,"end":95,"cssClass":"pl-s"},{"start":96,"end":97,"cssClass":"pl-kos"},{"start":97,"end":99,"cssClass":"pl-kos"},{"start":99,"end":100,"cssClass":"pl-ent"},{"start":100,"end":101,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":250,"end":252,"cssClass":"pl-kos"},{"start":252,"end":253,"cssClass":"pl-ent"},{"start":253,"end":254,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":65,"cssClass":"pl-s"},{"start":67,"end":72,"cssClass":"pl-c1"},{"start":74,"end":83,"cssClass":"pl-s"},{"start":85,"end":90,"cssClass":"pl-c1"},{"start":92,"end":95,"cssClass":"pl-s"},{"start":96,"end":97,"cssClass":"pl-kos"},{"start":97,"end":99,"cssClass":"pl-kos"},{"start":99,"end":100,"cssClass":"pl-ent"},{"start":100,"end":101,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":152,"end":154,"cssClass":"pl-kos"},{"start":154,"end":155,"cssClass":"pl-ent"},{"start":155,"end":156,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":95,"end":97,"cssClass":"pl-kos"},{"start":97,"end":98,"cssClass":"pl-ent"},{"start":98,"end":99,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":513,"end":515,"cssClass":"pl-kos"},{"start":515,"end":516,"cssClass":"pl-ent"},{"start":516,"end":517,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":487,"end":489,"cssClass":"pl-kos"},{"start":489,"end":490,"cssClass":"pl-ent"},{"start":490,"end":491,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":930,"end":932,"cssClass":"pl-kos"},{"start":932,"end":933,"cssClass":"pl-ent"},{"start":933,"end":934,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":20,"cssClass":"pl-s"},{"start":22,"end":27,"cssClass":"pl-c1"},{"start":29,"end":35,"cssClass":"pl-s"},{"start":36,"end":37,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":44,"cssClass":"pl-s"},{"start":45,"end":46,"cssClass":"pl-kos"},{"start":53,"end":55,"cssClass":"pl-kos"},{"start":55,"end":57,"cssClass":"pl-ent"},{"start":57,"end":58,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":1071,"end":1073,"cssClass":"pl-kos"},{"start":1073,"end":1074,"cssClass":"pl-ent"},{"start":1074,"end":1075,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":26,"cssClass":"pl-s"},{"start":28,"end":33,"cssClass":"pl-c1"},{"start":35,"end":41,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":50,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":65,"end":67,"cssClass":"pl-kos"},{"start":67,"end":69,"cssClass":"pl-ent"},{"start":69,"end":70,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":344,"end":345,"cssClass":"pl-kos"},{"start":345,"end":349,"cssClass":"pl-ent"},{"start":350,"end":355,"cssClass":"pl-c1"},{"start":357,"end":368,"cssClass":"pl-s"},{"start":369,"end":370,"cssClass":"pl-kos"},{"start":377,"end":379,"cssClass":"pl-kos"},{"start":379,"end":383,"cssClass":"pl-ent"},{"start":383,"end":384,"cssClass":"pl-kos"},{"start":609,"end":611,"cssClass":"pl-kos"},{"start":611,"end":612,"cssClass":"pl-ent"},{"start":612,"end":613,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":26,"cssClass":"pl-s"},{"start":28,"end":33,"cssClass":"pl-c1"},{"start":35,"end":41,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":50,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":65,"end":67,"cssClass":"pl-kos"},{"start":67,"end":69,"cssClass":"pl-ent"},{"start":69,"end":70,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":252,"end":253,"cssClass":"pl-kos"},{"start":253,"end":257,"cssClass":"pl-ent"},{"start":258,"end":263,"cssClass":"pl-c1"},{"start":265,"end":276,"cssClass":"pl-s"},{"start":277,"end":278,"cssClass":"pl-kos"},{"start":285,"end":287,"cssClass":"pl-kos"},{"start":287,"end":291,"cssClass":"pl-ent"},{"start":291,"end":292,"cssClass":"pl-kos"},{"start":663,"end":665,"cssClass":"pl-kos"},{"start":665,"end":666,"cssClass":"pl-ent"},{"start":666,"end":667,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":40,"cssClass":"pl-s"},{"start":42,"end":47,"cssClass":"pl-c1"},{"start":49,"end":55,"cssClass":"pl-s"},{"start":56,"end":57,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":64,"cssClass":"pl-s"},{"start":65,"end":66,"cssClass":"pl-kos"},{"start":93,"end":95,"cssClass":"pl-kos"},{"start":95,"end":97,"cssClass":"pl-ent"},{"start":97,"end":98,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":337,"end":338,"cssClass":"pl-kos"},{"start":338,"end":342,"cssClass":"pl-ent"},{"start":343,"end":348,"cssClass":"pl-c1"},{"start":350,"end":361,"cssClass":"pl-s"},{"start":362,"end":363,"cssClass":"pl-kos"},{"start":370,"end":372,"cssClass":"pl-kos"},{"start":372,"end":376,"cssClass":"pl-ent"},{"start":376,"end":377,"cssClass":"pl-kos"},{"start":392,"end":394,"cssClass":"pl-kos"},{"start":394,"end":395,"cssClass":"pl-ent"},{"start":395,"end":396,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":368,"end":370,"cssClass":"pl-kos"},{"start":370,"end":371,"cssClass":"pl-ent"},{"start":371,"end":372,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":25,"cssClass":"pl-c1"},{"start":27,"end":32,"cssClass":"pl-c1"},{"start":32,"end":33,"cssClass":"pl-kos"},{"start":40,"end":56,"cssClass":"pl-c1"},{"start":56,"end":57,"cssClass":"pl-kos"},{"start":65,"end":66,"cssClass":"pl-kos"},{"start":66,"end":83,"cssClass":"pl-c1"},{"start":84,"end":87,"cssClass":"pl-ent"},{"start":88,"end":95,"cssClass":"pl-c1"},{"start":95,"end":96,"cssClass":"pl-kos"},{"start":97,"end":98,"cssClass":"pl-c1"},{"start":100,"end":101,"cssClass":"pl-kos"},{"start":101,"end":118,"cssClass":"pl-c1"},{"start":119,"end":122,"cssClass":"pl-ent"},{"start":123,"end":136,"cssClass":"pl-c1"},{"start":138,"end":154,"cssClass":"pl-c1"},{"start":154,"end":155,"cssClass":"pl-kos"},{"start":163,"end":164,"cssClass":"pl-kos"},{"start":164,"end":181,"cssClass":"pl-c1"},{"start":182,"end":187,"cssClass":"pl-ent"},{"start":188,"end":208,"cssClass":"pl-c1"},{"start":210,"end":216,"cssClass":"pl-c1"},{"start":216,"end":217,"cssClass":"pl-kos"},{"start":226,"end":233,"cssClass":"pl-c1"},{"start":233,"end":234,"cssClass":"pl-kos"},{"start":241,"end":246,"cssClass":"pl-c1"},{"start":246,"end":247,"cssClass":"pl-kos"},{"start":248,"end":252,"cssClass":"pl-c1"},{"start":251,"end":252,"cssClass":"pl-smi"},{"start":253,"end":266,"cssClass":"pl-c1"},{"start":266,"end":267,"cssClass":"pl-kos"},{"start":268,"end":269,"cssClass":"pl-c1"},{"start":270,"end":277,"cssClass":"pl-c1"},{"start":277,"end":278,"cssClass":"pl-kos"},{"start":279,"end":284,"cssClass":"pl-c1"},{"start":282,"end":284,"cssClass":"pl-smi"},{"start":285,"end":295,"cssClass":"pl-c1"},{"start":295,"end":296,"cssClass":"pl-kos"},{"start":308,"end":318,"cssClass":"pl-c1"},{"start":318,"end":319,"cssClass":"pl-kos"},{"start":328,"end":329,"cssClass":"pl-kos"},{"start":329,"end":346,"cssClass":"pl-c1"},{"start":347,"end":352,"cssClass":"pl-ent"},{"start":353,"end":379,"cssClass":"pl-c1"},{"start":379,"end":380,"cssClass":"pl-kos"},{"start":380,"end":386,"cssClass":"pl-c1"},{"start":388,"end":395,"cssClass":"pl-c1"},{"start":395,"end":396,"cssClass":"pl-kos"},{"start":397,"end":400,"cssClass":"pl-s"},{"start":401,"end":406,"cssClass":"pl-c1"},{"start":406,"end":407,"cssClass":"pl-kos"},{"start":413,"end":425,"cssClass":"pl-c1"},{"start":425,"end":426,"cssClass":"pl-kos"},{"start":427,"end":433,"cssClass":"pl-c1"},{"start":431,"end":433,"cssClass":"pl-smi"},{"start":434,"end":439,"cssClass":"pl-c1"},{"start":439,"end":440,"cssClass":"pl-kos"},{"start":441,"end":448,"cssClass":"pl-pds"},{"start":441,"end":442,"cssClass":"pl-kos"},{"start":450,"end":451,"cssClass":"pl-kos"},{"start":451,"end":468,"cssClass":"pl-c1"},{"start":469,"end":474,"cssClass":"pl-ent"},{"start":475,"end":501,"cssClass":"pl-c1"},{"start":501,"end":502,"cssClass":"pl-kos"},{"start":502,"end":507,"cssClass":"pl-c1"},{"start":507,"end":508,"cssClass":"pl-kos"},{"start":508,"end":514,"cssClass":"pl-c1"},{"start":516,"end":521,"cssClass":"pl-c1"},{"start":521,"end":522,"cssClass":"pl-kos"},{"start":530,"end":531,"cssClass":"pl-kos"},{"start":531,"end":548,"cssClass":"pl-c1"},{"start":549,"end":552,"cssClass":"pl-ent"},{"start":553,"end":565,"cssClass":"pl-c1"},{"start":565,"end":566,"cssClass":"pl-kos"},{"start":566,"end":571,"cssClass":"pl-c1"},{"start":572,"end":577,"cssClass":"pl-ent"},{"start":578,"end":604,"cssClass":"pl-c1"},{"start":604,"end":605,"cssClass":"pl-kos"},{"start":605,"end":611,"cssClass":"pl-c1"},{"start":613,"end":618,"cssClass":"pl-c1"},{"start":618,"end":619,"cssClass":"pl-kos"},{"start":627,"end":628,"cssClass":"pl-kos"},{"start":628,"end":645,"cssClass":"pl-c1"},{"start":646,"end":649,"cssClass":"pl-ent"},{"start":650,"end":672,"cssClass":"pl-c1"},{"start":674,"end":684,"cssClass":"pl-c1"},{"start":684,"end":685,"cssClass":"pl-kos"},{"start":686,"end":687,"cssClass":"pl-c1"},{"start":688,"end":697,"cssClass":"pl-c1"},{"start":697,"end":698,"cssClass":"pl-kos"},{"start":699,"end":700,"cssClass":"pl-c1"},{"start":701,"end":709,"cssClass":"pl-c1"},{"start":709,"end":710,"cssClass":"pl-kos"},{"start":718,"end":728,"cssClass":"pl-c1"},{"start":728,"end":729,"cssClass":"pl-kos"},{"start":735,"end":751,"cssClass":"pl-c1"},{"start":751,"end":752,"cssClass":"pl-kos"},{"start":753,"end":760,"cssClass":"pl-pds"},{"start":753,"end":754,"cssClass":"pl-kos"},{"start":762,"end":763,"cssClass":"pl-kos"},{"start":763,"end":780,"cssClass":"pl-c1"},{"start":781,"end":784,"cssClass":"pl-ent"},{"start":785,"end":807,"cssClass":"pl-c1"},{"start":808,"end":811,"cssClass":"pl-ent"},{"start":813,"end":819,"cssClass":"pl-c1"},{"start":819,"end":820,"cssClass":"pl-kos"},{"start":821,"end":826,"cssClass":"pl-c1"},{"start":824,"end":826,"cssClass":"pl-smi"},{"start":827,"end":832,"cssClass":"pl-c1"},{"start":832,"end":833,"cssClass":"pl-kos"},{"start":840,"end":853,"cssClass":"pl-c1"},{"start":853,"end":854,"cssClass":"pl-kos"},{"start":855,"end":861,"cssClass":"pl-c1"},{"start":859,"end":861,"cssClass":"pl-smi"},{"start":862,"end":878,"cssClass":"pl-c1"},{"start":878,"end":879,"cssClass":"pl-kos"},{"start":880,"end":887,"cssClass":"pl-pds"},{"start":880,"end":881,"cssClass":"pl-kos"},{"start":889,"end":890,"cssClass":"pl-kos"},{"start":890,"end":907,"cssClass":"pl-c1"},{"start":908,"end":913,"cssClass":"pl-ent"},{"start":914,"end":936,"cssClass":"pl-c1"},{"start":936,"end":937,"cssClass":"pl-kos"},{"start":937,"end":944,"cssClass":"pl-c1"},{"start":944,"end":945,"cssClass":"pl-c1"},{"start":945,"end":948,"cssClass":"pl-ent"},{"start":949,"end":971,"cssClass":"pl-c1"},{"start":973,"end":983,"cssClass":"pl-c1"},{"start":983,"end":984,"cssClass":"pl-kos"},{"start":985,"end":990,"cssClass":"pl-c1"},{"start":988,"end":990,"cssClass":"pl-smi"},{"start":991,"end":1000,"cssClass":"pl-c1"},{"start":1000,"end":1001,"cssClass":"pl-kos"},{"start":1002,"end":1006,"cssClass":"pl-c1"},{"start":1005,"end":1006,"cssClass":"pl-smi"},{"start":1007,"end":1015,"cssClass":"pl-c1"},{"start":1015,"end":1016,"cssClass":"pl-kos"},{"start":1023,"end":1024,"cssClass":"pl-kos"},{"start":1024,"end":1041,"cssClass":"pl-c1"},{"start":1042,"end":1047,"cssClass":"pl-ent"},{"start":1048,"end":1070,"cssClass":"pl-c1"},{"start":1070,"end":1071,"cssClass":"pl-kos"},{"start":1071,"end":1078,"cssClass":"pl-c1"},{"start":1078,"end":1079,"cssClass":"pl-c1"},{"start":1079,"end":1084,"cssClass":"pl-ent"},{"start":1085,"end":1111,"cssClass":"pl-c1"},{"start":1111,"end":1112,"cssClass":"pl-kos"},{"start":1112,"end":1118,"cssClass":"pl-c1"},{"start":1120,"end":1127,"cssClass":"pl-c1"},{"start":1127,"end":1128,"cssClass":"pl-kos"},{"start":1129,"end":1132,"cssClass":"pl-s"},{"start":1134,"end":1135,"cssClass":"pl-kos"},{"start":1135,"end":1152,"cssClass":"pl-c1"},{"start":1153,"end":1156,"cssClass":"pl-ent"},{"start":1157,"end":1169,"cssClass":"pl-c1"},{"start":1170,"end":1175,"cssClass":"pl-ent"},{"start":1176,"end":1198,"cssClass":"pl-c1"},{"start":1198,"end":1199,"cssClass":"pl-kos"},{"start":1199,"end":1206,"cssClass":"pl-c1"},{"start":1206,"end":1207,"cssClass":"pl-c1"},{"start":1207,"end":1212,"cssClass":"pl-ent"},{"start":1213,"end":1233,"cssClass":"pl-c1"},{"start":1235,"end":1251,"cssClass":"pl-c1"},{"start":1251,"end":1252,"cssClass":"pl-kos"},{"start":1253,"end":1260,"cssClass":"pl-pds"},{"start":1253,"end":1254,"cssClass":"pl-kos"},{"start":1262,"end":1263,"cssClass":"pl-kos"},{"start":1263,"end":1280,"cssClass":"pl-c1"},{"start":1281,"end":1284,"cssClass":"pl-ent"},{"start":1285,"end":1293,"cssClass":"pl-c1"},{"start":1294,"end":1299,"cssClass":"pl-ent"},{"start":1300,"end":1322,"cssClass":"pl-c1"},{"start":1322,"end":1323,"cssClass":"pl-kos"},{"start":1323,"end":1330,"cssClass":"pl-c1"},{"start":1330,"end":1331,"cssClass":"pl-c1"},{"start":1331,"end":1336,"cssClass":"pl-ent"},{"start":1337,"end":1357,"cssClass":"pl-c1"},{"start":1359,"end":1375,"cssClass":"pl-c1"},{"start":1375,"end":1376,"cssClass":"pl-kos"},{"start":1377,"end":1384,"cssClass":"pl-pds"},{"start":1377,"end":1378,"cssClass":"pl-kos"},{"start":1386,"end":1387,"cssClass":"pl-kos"},{"start":1387,"end":1404,"cssClass":"pl-c1"},{"start":1405,"end":1410,"cssClass":"pl-ent"},{"start":1411,"end":1430,"cssClass":"pl-c1"},{"start":1432,"end":1438,"cssClass":"pl-c1"},{"start":1438,"end":1439,"cssClass":"pl-kos"},{"start":1440,"end":1441,"cssClass":"pl-c1"},{"start":1442,"end":1446,"cssClass":"pl-c1"},{"start":1446,"end":1447,"cssClass":"pl-kos"},{"start":1448,"end":1452,"cssClass":"pl-en"},{"start":1453,"end":1456,"cssClass":"pl-c1"},{"start":1454,"end":1456,"cssClass":"pl-smi"},{"start":1457,"end":1460,"cssClass":"pl-c1"},{"start":1458,"end":1460,"cssClass":"pl-smi"},{"start":1461,"end":1464,"cssClass":"pl-c1"},{"start":1462,"end":1464,"cssClass":"pl-smi"},{"start":1465,"end":1468,"cssClass":"pl-c1"},{"start":1466,"end":1468,"cssClass":"pl-smi"},{"start":1470,"end":1474,"cssClass":"pl-c1"},{"start":1474,"end":1475,"cssClass":"pl-kos"},{"start":1476,"end":1480,"cssClass":"pl-en"},{"start":1481,"end":1484,"cssClass":"pl-c1"},{"start":1482,"end":1484,"cssClass":"pl-smi"},{"start":1484,"end":1485,"cssClass":"pl-kos"},{"start":1486,"end":1489,"cssClass":"pl-c1"},{"start":1487,"end":1489,"cssClass":"pl-smi"},{"start":1489,"end":1490,"cssClass":"pl-kos"},{"start":1491,"end":1494,"cssClass":"pl-c1"},{"start":1492,"end":1494,"cssClass":"pl-smi"},{"start":1494,"end":1495,"cssClass":"pl-kos"},{"start":1496,"end":1499,"cssClass":"pl-c1"},{"start":1497,"end":1499,"cssClass":"pl-smi"},{"start":1501,"end":1507,"cssClass":"pl-c1"},{"start":1507,"end":1508,"cssClass":"pl-kos"},{"start":1509,"end":1512,"cssClass":"pl-c1"},{"start":1510,"end":1512,"cssClass":"pl-smi"},{"start":1513,"end":1519,"cssClass":"pl-c1"},{"start":1519,"end":1520,"cssClass":"pl-kos"},{"start":1521,"end":1525,"cssClass":"pl-c1"},{"start":1523,"end":1525,"cssClass":"pl-smi"},{"start":1526,"end":1534,"cssClass":"pl-c1"},{"start":1534,"end":1535,"cssClass":"pl-kos"},{"start":1543,"end":1550,"cssClass":"pl-c1"},{"start":1550,"end":1551,"cssClass":"pl-kos"},{"start":1552,"end":1553,"cssClass":"pl-c1"},{"start":1554,"end":1562,"cssClass":"pl-c1"},{"start":1562,"end":1563,"cssClass":"pl-kos"},{"start":1573,"end":1578,"cssClass":"pl-c1"},{"start":1578,"end":1579,"cssClass":"pl-kos"},{"start":1580,"end":1583,"cssClass":"pl-c1"},{"start":1581,"end":1583,"cssClass":"pl-smi"},{"start":1585,"end":1586,"cssClass":"pl-kos"},{"start":1586,"end":1603,"cssClass":"pl-c1"},{"start":1604,"end":1607,"cssClass":"pl-ent"},{"start":1608,"end":1620,"cssClass":"pl-c1"},{"start":1622,"end":1633,"cssClass":"pl-c1"},{"start":1633,"end":1634,"cssClass":"pl-kos"},{"start":1645,"end":1661,"cssClass":"pl-c1"},{"start":1661,"end":1662,"cssClass":"pl-kos"},{"start":1663,"end":1670,"cssClass":"pl-pds"},{"start":1663,"end":1664,"cssClass":"pl-kos"},{"start":1671,"end":1677,"cssClass":"pl-c1"},{"start":1677,"end":1678,"cssClass":"pl-kos"},{"start":1679,"end":1682,"cssClass":"pl-c1"},{"start":1680,"end":1682,"cssClass":"pl-smi"},{"start":1696,"end":1709,"cssClass":"pl-c1"},{"start":1709,"end":1710,"cssClass":"pl-kos"},{"start":1711,"end":1717,"cssClass":"pl-c1"},{"start":1715,"end":1717,"cssClass":"pl-smi"},{"start":1718,"end":1728,"cssClass":"pl-c1"},{"start":1728,"end":1729,"cssClass":"pl-kos"},{"start":1741,"end":1754,"cssClass":"pl-c1"},{"start":1754,"end":1755,"cssClass":"pl-kos"},{"start":1756,"end":1761,"cssClass":"pl-c1"},{"start":1759,"end":1761,"cssClass":"pl-smi"},{"start":1763,"end":1764,"cssClass":"pl-kos"},{"start":1764,"end":1781,"cssClass":"pl-c1"},{"start":1782,"end":1785,"cssClass":"pl-ent"},{"start":1786,"end":1798,"cssClass":"pl-c1"},{"start":1798,"end":1799,"cssClass":"pl-kos"},{"start":1799,"end":1804,"cssClass":"pl-c1"},{"start":1806,"end":1822,"cssClass":"pl-c1"},{"start":1822,"end":1823,"cssClass":"pl-kos"},{"start":1824,"end":1831,"cssClass":"pl-pds"},{"start":1824,"end":1825,"cssClass":"pl-kos"},{"start":1833,"end":1834,"cssClass":"pl-kos"},{"start":1834,"end":1851,"cssClass":"pl-c1"},{"start":1852,"end":1855,"cssClass":"pl-ent"},{"start":1856,"end":1872,"cssClass":"pl-c1"},{"start":1874,"end":1879,"cssClass":"pl-ent"},{"start":1881,"end":1888,"cssClass":"pl-c1"},{"start":1888,"end":1889,"cssClass":"pl-kos"},{"start":1890,"end":1892,"cssClass":"pl-s"},{"start":1893,"end":1898,"cssClass":"pl-c1"},{"start":1898,"end":1899,"cssClass":"pl-kos"},{"start":1900,"end":1904,"cssClass":"pl-c1"},{"start":1903,"end":1904,"cssClass":"pl-smi"},{"start":1905,"end":1918,"cssClass":"pl-c1"},{"start":1918,"end":1919,"cssClass":"pl-kos"},{"start":1920,"end":1923,"cssClass":"pl-c1"},{"start":1921,"end":1923,"cssClass":"pl-smi"},{"start":1935,"end":1944,"cssClass":"pl-c1"},{"start":1944,"end":1945,"cssClass":"pl-kos"},{"start":1946,"end":1947,"cssClass":"pl-c1"},{"start":1949,"end":1950,"cssClass":"pl-kos"},{"start":1950,"end":1967,"cssClass":"pl-c1"},{"start":1968,"end":1971,"cssClass":"pl-ent"},{"start":1972,"end":1980,"cssClass":"pl-c1"},{"start":1980,"end":1981,"cssClass":"pl-kos"},{"start":1981,"end":1986,"cssClass":"pl-c1"},{"start":1987,"end":1992,"cssClass":"pl-ent"},{"start":1993,"end":2013,"cssClass":"pl-c1"},{"start":2015,"end":2031,"cssClass":"pl-c1"},{"start":2031,"end":2032,"cssClass":"pl-kos"},{"start":2033,"end":2040,"cssClass":"pl-pds"},{"start":2033,"end":2034,"cssClass":"pl-kos"},{"start":2042,"end":2043,"cssClass":"pl-kos"},{"start":2043,"end":2060,"cssClass":"pl-c1"},{"start":2061,"end":2064,"cssClass":"pl-ent"},{"start":2065,"end":2074,"cssClass":"pl-c1"},{"start":2076,"end":2082,"cssClass":"pl-ent"},{"start":2084,"end":2091,"cssClass":"pl-c1"},{"start":2091,"end":2092,"cssClass":"pl-kos"},{"start":2093,"end":2095,"cssClass":"pl-s"},{"start":2096,"end":2104,"cssClass":"pl-c1"},{"start":2104,"end":2105,"cssClass":"pl-kos"},{"start":2115,"end":2126,"cssClass":"pl-c1"},{"start":2126,"end":2127,"cssClass":"pl-kos"},{"start":2128,"end":2131,"cssClass":"pl-c1"},{"start":2129,"end":2131,"cssClass":"pl-smi"},{"start":2143,"end":2153,"cssClass":"pl-c1"},{"start":2153,"end":2154,"cssClass":"pl-kos"},{"start":2166,"end":2169,"cssClass":"pl-c1"},{"start":2169,"end":2170,"cssClass":"pl-kos"},{"start":2171,"end":2172,"cssClass":"pl-c1"},{"start":2173,"end":2179,"cssClass":"pl-c1"},{"start":2179,"end":2180,"cssClass":"pl-kos"},{"start":2181,"end":2182,"cssClass":"pl-c1"},{"start":2183,"end":2187,"cssClass":"pl-c1"},{"start":2187,"end":2188,"cssClass":"pl-kos"},{"start":2189,"end":2192,"cssClass":"pl-c1"},{"start":2191,"end":2192,"cssClass":"pl-smi"},{"start":2193,"end":2200,"cssClass":"pl-c1"},{"start":2200,"end":2201,"cssClass":"pl-kos"},{"start":2202,"end":2203,"cssClass":"pl-c1"},{"start":2205,"end":2206,"cssClass":"pl-kos"},{"start":2206,"end":2223,"cssClass":"pl-c1"},{"start":2224,"end":2227,"cssClass":"pl-ent"},{"start":2228,"end":2237,"cssClass":"pl-c1"},{"start":2239,"end":2246,"cssClass":"pl-c1"},{"start":2246,"end":2247,"cssClass":"pl-kos"},{"start":2253,"end":2267,"cssClass":"pl-c1"},{"start":2267,"end":2268,"cssClass":"pl-kos"},{"start":2276,"end":2287,"cssClass":"pl-c1"},{"start":2287,"end":2288,"cssClass":"pl-kos"},{"start":2296,"end":2312,"cssClass":"pl-c1"},{"start":2312,"end":2313,"cssClass":"pl-kos"},{"start":2320,"end":2333,"cssClass":"pl-c1"},{"start":2333,"end":2334,"cssClass":"pl-kos"},{"start":2335,"end":2340,"cssClass":"pl-c1"},{"start":2338,"end":2340,"cssClass":"pl-smi"},{"start":2341,"end":2353,"cssClass":"pl-c1"},{"start":2353,"end":2354,"cssClass":"pl-kos"},{"start":2355,"end":2360,"cssClass":"pl-c1"},{"start":2358,"end":2360,"cssClass":"pl-smi"},{"start":2361,"end":2369,"cssClass":"pl-c1"},{"start":2369,"end":2370,"cssClass":"pl-kos"},{"start":2381,"end":2382,"cssClass":"pl-kos"},{"start":2382,"end":2399,"cssClass":"pl-c1"},{"start":2400,"end":2403,"cssClass":"pl-ent"},{"start":2404,"end":2411,"cssClass":"pl-c1"},{"start":2413,"end":2421,"cssClass":"pl-c1"},{"start":2421,"end":2422,"cssClass":"pl-kos"},{"start":2432,"end":2439,"cssClass":"pl-c1"},{"start":2439,"end":2440,"cssClass":"pl-kos"},{"start":2441,"end":2442,"cssClass":"pl-c1"},{"start":2444,"end":2445,"cssClass":"pl-kos"},{"start":2445,"end":2462,"cssClass":"pl-c1"},{"start":2463,"end":2466,"cssClass":"pl-ent"},{"start":2467,"end":2478,"cssClass":"pl-c1"},{"start":2480,"end":2487,"cssClass":"pl-c1"},{"start":2487,"end":2488,"cssClass":"pl-kos"},{"start":2494,"end":2505,"cssClass":"pl-c1"},{"start":2505,"end":2506,"cssClass":"pl-kos"},{"start":2515,"end":2530,"cssClass":"pl-c1"},{"start":2530,"end":2531,"cssClass":"pl-kos"},{"start":2539,"end":2555,"cssClass":"pl-c1"},{"start":2555,"end":2556,"cssClass":"pl-kos"},{"start":2563,"end":2571,"cssClass":"pl-c1"},{"start":2571,"end":2572,"cssClass":"pl-kos"},{"start":2583,"end":2584,"cssClass":"pl-kos"},{"start":2584,"end":2601,"cssClass":"pl-c1"},{"start":2602,"end":2605,"cssClass":"pl-ent"},{"start":2606,"end":2613,"cssClass":"pl-c1"},{"start":2615,"end":2621,"cssClass":"pl-ent"},{"start":2621,"end":2622,"cssClass":"pl-kos"},{"start":2623,"end":2624,"cssClass":"pl-kos"},{"start":2624,"end":2641,"cssClass":"pl-c1"},{"start":2642,"end":2645,"cssClass":"pl-ent"},{"start":2646,"end":2662,"cssClass":"pl-c1"},{"start":2664,"end":2670,"cssClass":"pl-ent"},{"start":2672,"end":2679,"cssClass":"pl-c1"},{"start":2679,"end":2680,"cssClass":"pl-kos"},{"start":2681,"end":2683,"cssClass":"pl-s"},{"start":2684,"end":2692,"cssClass":"pl-c1"},{"start":2692,"end":2693,"cssClass":"pl-kos"},{"start":2703,"end":2714,"cssClass":"pl-c1"},{"start":2714,"end":2715,"cssClass":"pl-kos"},{"start":2716,"end":2719,"cssClass":"pl-c1"},{"start":2717,"end":2719,"cssClass":"pl-smi"},{"start":2731,"end":2741,"cssClass":"pl-c1"},{"start":2741,"end":2742,"cssClass":"pl-kos"},{"start":2754,"end":2757,"cssClass":"pl-c1"},{"start":2757,"end":2758,"cssClass":"pl-kos"},{"start":2759,"end":2760,"cssClass":"pl-c1"},{"start":2761,"end":2767,"cssClass":"pl-c1"},{"start":2767,"end":2768,"cssClass":"pl-kos"},{"start":2769,"end":2770,"cssClass":"pl-c1"},{"start":2771,"end":2775,"cssClass":"pl-c1"},{"start":2775,"end":2776,"cssClass":"pl-kos"},{"start":2777,"end":2780,"cssClass":"pl-c1"},{"start":2779,"end":2780,"cssClass":"pl-smi"},{"start":2781,"end":2788,"cssClass":"pl-c1"},{"start":2788,"end":2789,"cssClass":"pl-kos"},{"start":2790,"end":2792,"cssClass":"pl-c1"},{"start":2794,"end":2795,"cssClass":"pl-kos"},{"start":2795,"end":2812,"cssClass":"pl-c1"},{"start":2813,"end":2816,"cssClass":"pl-ent"},{"start":2817,"end":2833,"cssClass":"pl-c1"},{"start":2835,"end":2842,"cssClass":"pl-c1"},{"start":2842,"end":2843,"cssClass":"pl-kos"},{"start":2849,"end":2863,"cssClass":"pl-c1"},{"start":2863,"end":2864,"cssClass":"pl-kos"},{"start":2872,"end":2879,"cssClass":"pl-c1"},{"start":2879,"end":2880,"cssClass":"pl-kos"},{"start":2881,"end":2882,"cssClass":"pl-c1"},{"start":2883,"end":2891,"cssClass":"pl-c1"},{"start":2891,"end":2892,"cssClass":"pl-kos"},{"start":2902,"end":2918,"cssClass":"pl-c1"},{"start":2918,"end":2919,"cssClass":"pl-kos"},{"start":2927,"end":2928,"cssClass":"pl-kos"},{"start":2928,"end":2945,"cssClass":"pl-c1"},{"start":2946,"end":2949,"cssClass":"pl-ent"},{"start":2950,"end":2966,"cssClass":"pl-c1"},{"start":2966,"end":2967,"cssClass":"pl-kos"},{"start":2967,"end":2978,"cssClass":"pl-c1"},{"start":2980,"end":2985,"cssClass":"pl-ent"},{"start":2987,"end":2997,"cssClass":"pl-c1"},{"start":2997,"end":2998,"cssClass":"pl-kos"},{"start":3008,"end":3013,"cssClass":"pl-c1"},{"start":3013,"end":3014,"cssClass":"pl-kos"},{"start":3015,"end":3018,"cssClass":"pl-c1"},{"start":3017,"end":3018,"cssClass":"pl-smi"},{"start":3020,"end":3021,"cssClass":"pl-kos"},{"start":3021,"end":3038,"cssClass":"pl-c1"},{"start":3039,"end":3042,"cssClass":"pl-ent"},{"start":3043,"end":3059,"cssClass":"pl-c1"},{"start":3059,"end":3060,"cssClass":"pl-kos"},{"start":3060,"end":3070,"cssClass":"pl-c1"},{"start":3072,"end":3077,"cssClass":"pl-ent"},{"start":3079,"end":3089,"cssClass":"pl-c1"},{"start":3089,"end":3090,"cssClass":"pl-kos"},{"start":3102,"end":3107,"cssClass":"pl-c1"},{"start":3107,"end":3108,"cssClass":"pl-kos"},{"start":3109,"end":3112,"cssClass":"pl-c1"},{"start":3111,"end":3112,"cssClass":"pl-smi"},{"start":3114,"end":3115,"cssClass":"pl-kos"},{"start":3115,"end":3132,"cssClass":"pl-c1"},{"start":3133,"end":3136,"cssClass":"pl-ent"},{"start":3137,"end":3153,"cssClass":"pl-c1"},{"start":3153,"end":3154,"cssClass":"pl-kos"},{"start":3154,"end":3164,"cssClass":"pl-c1"},{"start":3166,"end":3171,"cssClass":"pl-ent"},{"start":3173,"end":3178,"cssClass":"pl-c1"},{"start":3178,"end":3179,"cssClass":"pl-kos"},{"start":3180,"end":3181,"cssClass":"pl-c1"},{"start":3183,"end":3184,"cssClass":"pl-kos"},{"start":3184,"end":3201,"cssClass":"pl-c1"},{"start":3202,"end":3205,"cssClass":"pl-ent"},{"start":3206,"end":3223,"cssClass":"pl-c1"},{"start":3225,"end":3231,"cssClass":"pl-c1"},{"start":3231,"end":3232,"cssClass":"pl-kos"},{"start":3233,"end":3236,"cssClass":"pl-c1"},{"start":3234,"end":3236,"cssClass":"pl-smi"},{"start":3249,"end":3255,"cssClass":"pl-c1"},{"start":3255,"end":3256,"cssClass":"pl-kos"},{"start":3257,"end":3258,"cssClass":"pl-c1"},{"start":3259,"end":3264,"cssClass":"pl-c1"},{"start":3262,"end":3264,"cssClass":"pl-smi"},{"start":3265,"end":3270,"cssClass":"pl-c1"},{"start":3268,"end":3270,"cssClass":"pl-smi"},{"start":3271,"end":3276,"cssClass":"pl-c1"},{"start":3274,"end":3276,"cssClass":"pl-smi"},{"start":3277,"end":3287,"cssClass":"pl-c1"},{"start":3287,"end":3288,"cssClass":"pl-kos"},{"start":3300,"end":3314,"cssClass":"pl-c1"},{"start":3314,"end":3315,"cssClass":"pl-kos"},{"start":3316,"end":3321,"cssClass":"pl-c1"},{"start":3319,"end":3321,"cssClass":"pl-smi"},{"start":3322,"end":3338,"cssClass":"pl-c1"},{"start":3338,"end":3339,"cssClass":"pl-kos"},{"start":3347,"end":3348,"cssClass":"pl-kos"},{"start":3348,"end":3365,"cssClass":"pl-c1"},{"start":3366,"end":3369,"cssClass":"pl-ent"},{"start":3370,"end":3378,"cssClass":"pl-c1"},{"start":3379,"end":3384,"cssClass":"pl-ent"},{"start":3386,"end":3397,"cssClass":"pl-c1"},{"start":3397,"end":3398,"cssClass":"pl-kos"},{"start":3409,"end":3420,"cssClass":"pl-c1"},{"start":3420,"end":3421,"cssClass":"pl-kos"},{"start":3427,"end":3434,"cssClass":"pl-c1"},{"start":3434,"end":3435,"cssClass":"pl-kos"},{"start":3449,"end":3460,"cssClass":"pl-c1"},{"start":3460,"end":3461,"cssClass":"pl-kos"},{"start":3462,"end":3467,"cssClass":"pl-c1"},{"start":3465,"end":3467,"cssClass":"pl-smi"},{"start":3469,"end":3470,"cssClass":"pl-kos"},{"start":3470,"end":3487,"cssClass":"pl-c1"},{"start":3488,"end":3491,"cssClass":"pl-ent"},{"start":3492,"end":3510,"cssClass":"pl-c1"},{"start":3512,"end":3522,"cssClass":"pl-c1"},{"start":3522,"end":3523,"cssClass":"pl-kos"},{"start":3532,"end":3533,"cssClass":"pl-kos"},{"start":3533,"end":3550,"cssClass":"pl-c1"},{"start":3551,"end":3554,"cssClass":"pl-ent"},{"start":3555,"end":3567,"cssClass":"pl-c1"},{"start":3569,"end":3896,"cssClass":"pl-c"},{"start":3896,"end":3903,"cssClass":"pl-c1"},{"start":3903,"end":3904,"cssClass":"pl-kos"},{"start":3918,"end":3928,"cssClass":"pl-k"},{"start":3929,"end":3937,"cssClass":"pl-c1"},{"start":3937,"end":3938,"cssClass":"pl-kos"},{"start":3949,"end":3950,"cssClass":"pl-kos"},{"start":3950,"end":3967,"cssClass":"pl-c1"},{"start":3968,"end":3971,"cssClass":"pl-ent"},{"start":3972,"end":3993,"cssClass":"pl-c1"},{"start":3995,"end":4002,"cssClass":"pl-c1"},{"start":4002,"end":4003,"cssClass":"pl-kos"},{"start":4010,"end":4012,"cssClass":"pl-kos"},{"start":4012,"end":4017,"cssClass":"pl-ent"},{"start":4017,"end":4018,"cssClass":"pl-kos"},{"start":4018,"end":4019,"cssClass":"pl-kos"},{"start":4019,"end":4022,"cssClass":"pl-ent"},{"start":4023,"end":4025,"cssClass":"pl-c1"},{"start":4027,"end":4044,"cssClass":"pl-s"},{"start":4046,"end":4051,"cssClass":"pl-c1"},{"start":4053,"end":4069,"cssClass":"pl-s"},{"start":4070,"end":4071,"cssClass":"pl-kos"},{"start":4071,"end":4072,"cssClass":"pl-kos"},{"start":4072,"end":4075,"cssClass":"pl-ent"},{"start":4076,"end":4081,"cssClass":"pl-c1"},{"start":4083,"end":4104,"cssClass":"pl-s"},{"start":4105,"end":4106,"cssClass":"pl-kos"},{"start":4106,"end":4107,"cssClass":"pl-kos"},{"start":4107,"end":4110,"cssClass":"pl-ent"},{"start":4110,"end":4111,"cssClass":"pl-kos"}],[],[],[],[],[{"start":61,"end":63,"cssClass":"pl-kos"},{"start":63,"end":66,"cssClass":"pl-ent"},{"start":66,"end":67,"cssClass":"pl-kos"},{"start":67,"end":68,"cssClass":"pl-kos"},{"start":68,"end":69,"cssClass":"pl-ent"},{"start":69,"end":70,"cssClass":"pl-kos"},{"start":174,"end":175,"cssClass":"pl-kos"},{"start":175,"end":177,"cssClass":"pl-ent"},{"start":177,"end":178,"cssClass":"pl-kos"},{"start":281,"end":283,"cssClass":"pl-kos"},{"start":283,"end":284,"cssClass":"pl-ent"},{"start":284,"end":285,"cssClass":"pl-kos"},{"start":285,"end":287,"cssClass":"pl-kos"},{"start":287,"end":290,"cssClass":"pl-ent"},{"start":290,"end":291,"cssClass":"pl-kos"},{"start":291,"end":292,"cssClass":"pl-kos"},{"start":292,"end":295,"cssClass":"pl-ent"},{"start":296,"end":301,"cssClass":"pl-c1"},{"start":303,"end":315,"cssClass":"pl-s"},{"start":317,"end":323,"cssClass":"pl-c1"},{"start":326,"end":327,"cssClass":"pl-kos"},{"start":327,"end":328,"cssClass":"pl-kos"},{"start":328,"end":331,"cssClass":"pl-ent"},{"start":332,"end":337,"cssClass":"pl-c1"},{"start":339,"end":364,"cssClass":"pl-s"},{"start":365,"end":366,"cssClass":"pl-kos"},{"start":366,"end":367,"cssClass":"pl-kos"},{"start":367,"end":370,"cssClass":"pl-ent"},{"start":371,"end":376,"cssClass":"pl-c1"},{"start":378,"end":396,"cssClass":"pl-s"},{"start":397,"end":398,"cssClass":"pl-kos"},{"start":398,"end":399,"cssClass":"pl-kos"},{"start":399,"end":402,"cssClass":"pl-ent"},{"start":403,"end":408,"cssClass":"pl-c1"},{"start":410,"end":432,"cssClass":"pl-s"},{"start":433,"end":434,"cssClass":"pl-kos"},{"start":434,"end":435,"cssClass":"pl-kos"},{"start":435,"end":440,"cssClass":"pl-ent"},{"start":441,"end":446,"cssClass":"pl-c1"},{"start":448,"end":490,"cssClass":"pl-s"},{"start":492,"end":494,"cssClass":"pl-c1"},{"start":496,"end":513,"cssClass":"pl-s"},{"start":515,"end":519,"cssClass":"pl-c1"},{"start":521,"end":529,"cssClass":"pl-s"},{"start":530,"end":531,"cssClass":"pl-kos"},{"start":531,"end":532,"cssClass":"pl-kos"},{"start":532,"end":537,"cssClass":"pl-ent"},{"start":538,"end":541,"cssClass":"pl-c1"},{"start":543,"end":560,"cssClass":"pl-s"},{"start":562,"end":567,"cssClass":"pl-c1"},{"start":569,"end":616,"cssClass":"pl-s"},{"start":617,"end":618,"cssClass":"pl-kos"},{"start":626,"end":628,"cssClass":"pl-kos"},{"start":628,"end":633,"cssClass":"pl-ent"},{"start":633,"end":634,"cssClass":"pl-kos"},{"start":634,"end":635,"cssClass":"pl-kos"},{"start":635,"end":638,"cssClass":"pl-ent"},{"start":639,"end":644,"cssClass":"pl-c1"},{"start":646,"end":668,"cssClass":"pl-s"},{"start":669,"end":670,"cssClass":"pl-kos"},{"start":670,"end":671,"cssClass":"pl-kos"},{"start":671,"end":674,"cssClass":"pl-ent"},{"start":674,"end":675,"cssClass":"pl-kos"}],[],[],[],[],[{"start":61,"end":63,"cssClass":"pl-kos"},{"start":63,"end":66,"cssClass":"pl-ent"},{"start":66,"end":67,"cssClass":"pl-kos"},{"start":67,"end":69,"cssClass":"pl-kos"},{"start":69,"end":72,"cssClass":"pl-ent"},{"start":72,"end":73,"cssClass":"pl-kos"},{"start":73,"end":75,"cssClass":"pl-kos"},{"start":75,"end":78,"cssClass":"pl-ent"},{"start":78,"end":79,"cssClass":"pl-kos"},{"start":79,"end":81,"cssClass":"pl-kos"},{"start":81,"end":84,"cssClass":"pl-ent"},{"start":84,"end":85,"cssClass":"pl-kos"},{"start":85,"end":86,"cssClass":"pl-kos"},{"start":86,"end":89,"cssClass":"pl-ent"},{"start":90,"end":95,"cssClass":"pl-c1"},{"start":97,"end":106,"cssClass":"pl-s"},{"start":107,"end":108,"cssClass":"pl-kos"},{"start":108,"end":109,"cssClass":"pl-kos"},{"start":109,"end":112,"cssClass":"pl-ent"},{"start":113,"end":118,"cssClass":"pl-c1"},{"start":120,"end":145,"cssClass":"pl-s"},{"start":146,"end":147,"cssClass":"pl-kos"},{"start":147,"end":148,"cssClass":"pl-kos"},{"start":148,"end":151,"cssClass":"pl-ent"},{"start":152,"end":157,"cssClass":"pl-c1"},{"start":159,"end":177,"cssClass":"pl-s"},{"start":178,"end":179,"cssClass":"pl-kos"},{"start":179,"end":180,"cssClass":"pl-kos"},{"start":180,"end":183,"cssClass":"pl-ent"},{"start":184,"end":189,"cssClass":"pl-c1"},{"start":191,"end":213,"cssClass":"pl-s"},{"start":214,"end":215,"cssClass":"pl-kos"},{"start":215,"end":216,"cssClass":"pl-kos"},{"start":216,"end":221,"cssClass":"pl-ent"},{"start":222,"end":227,"cssClass":"pl-c1"},{"start":229,"end":271,"cssClass":"pl-s"},{"start":273,"end":275,"cssClass":"pl-c1"},{"start":277,"end":294,"cssClass":"pl-s"},{"start":296,"end":300,"cssClass":"pl-c1"},{"start":302,"end":310,"cssClass":"pl-s"},{"start":311,"end":312,"cssClass":"pl-kos"},{"start":312,"end":313,"cssClass":"pl-kos"},{"start":313,"end":318,"cssClass":"pl-ent"},{"start":319,"end":322,"cssClass":"pl-c1"},{"start":324,"end":341,"cssClass":"pl-s"},{"start":343,"end":348,"cssClass":"pl-c1"},{"start":350,"end":397,"cssClass":"pl-s"},{"start":398,"end":399,"cssClass":"pl-kos"},{"start":430,"end":432,"cssClass":"pl-kos"},{"start":432,"end":437,"cssClass":"pl-ent"},{"start":437,"end":438,"cssClass":"pl-kos"},{"start":438,"end":439,"cssClass":"pl-kos"},{"start":439,"end":442,"cssClass":"pl-ent"},{"start":443,"end":448,"cssClass":"pl-c1"},{"start":450,"end":472,"cssClass":"pl-s"},{"start":473,"end":474,"cssClass":"pl-kos"},{"start":474,"end":475,"cssClass":"pl-kos"},{"start":475,"end":478,"cssClass":"pl-ent"},{"start":478,"end":479,"cssClass":"pl-kos"}],[{"start":79,"end":81,"cssClass":"pl-kos"},{"start":81,"end":84,"cssClass":"pl-ent"},{"start":84,"end":85,"cssClass":"pl-kos"},{"start":85,"end":87,"cssClass":"pl-kos"},{"start":87,"end":90,"cssClass":"pl-ent"},{"start":90,"end":91,"cssClass":"pl-kos"},{"start":91,"end":93,"cssClass":"pl-kos"},{"start":93,"end":96,"cssClass":"pl-ent"},{"start":96,"end":97,"cssClass":"pl-kos"},{"start":97,"end":99,"cssClass":"pl-kos"},{"start":99,"end":102,"cssClass":"pl-ent"},{"start":102,"end":103,"cssClass":"pl-kos"},{"start":103,"end":104,"cssClass":"pl-kos"},{"start":104,"end":107,"cssClass":"pl-ent"},{"start":108,"end":113,"cssClass":"pl-c1"},{"start":115,"end":126,"cssClass":"pl-s"},{"start":127,"end":128,"cssClass":"pl-kos"},{"start":128,"end":129,"cssClass":"pl-kos"},{"start":129,"end":132,"cssClass":"pl-ent"},{"start":133,"end":138,"cssClass":"pl-c1"},{"start":140,"end":156,"cssClass":"pl-s"},{"start":157,"end":158,"cssClass":"pl-kos"},{"start":158,"end":159,"cssClass":"pl-kos"},{"start":159,"end":162,"cssClass":"pl-ent"},{"start":163,"end":168,"cssClass":"pl-c1"},{"start":170,"end":177,"cssClass":"pl-s"},{"start":178,"end":179,"cssClass":"pl-kos"},{"start":179,"end":180,"cssClass":"pl-kos"},{"start":180,"end":183,"cssClass":"pl-ent"},{"start":184,"end":189,"cssClass":"pl-c1"},{"start":191,"end":209,"cssClass":"pl-s"},{"start":210,"end":211,"cssClass":"pl-kos"},{"start":211,"end":212,"cssClass":"pl-kos"},{"start":212,"end":215,"cssClass":"pl-ent"},{"start":216,"end":221,"cssClass":"pl-c1"},{"start":223,"end":245,"cssClass":"pl-s"},{"start":246,"end":247,"cssClass":"pl-kos"},{"start":247,"end":248,"cssClass":"pl-kos"},{"start":248,"end":253,"cssClass":"pl-ent"},{"start":254,"end":259,"cssClass":"pl-c1"},{"start":261,"end":303,"cssClass":"pl-s"},{"start":305,"end":307,"cssClass":"pl-c1"},{"start":309,"end":326,"cssClass":"pl-s"},{"start":328,"end":332,"cssClass":"pl-c1"},{"start":334,"end":342,"cssClass":"pl-s"},{"start":343,"end":344,"cssClass":"pl-kos"},{"start":344,"end":345,"cssClass":"pl-kos"},{"start":345,"end":350,"cssClass":"pl-ent"},{"start":351,"end":354,"cssClass":"pl-c1"},{"start":356,"end":373,"cssClass":"pl-s"},{"start":375,"end":380,"cssClass":"pl-c1"},{"start":382,"end":429,"cssClass":"pl-s"},{"start":430,"end":431,"cssClass":"pl-kos"},{"start":445,"end":447,"cssClass":"pl-kos"},{"start":447,"end":452,"cssClass":"pl-ent"},{"start":452,"end":453,"cssClass":"pl-kos"},{"start":453,"end":454,"cssClass":"pl-kos"},{"start":454,"end":457,"cssClass":"pl-ent"},{"start":458,"end":463,"cssClass":"pl-c1"},{"start":465,"end":487,"cssClass":"pl-s"},{"start":488,"end":489,"cssClass":"pl-kos"},{"start":489,"end":490,"cssClass":"pl-kos"},{"start":490,"end":493,"cssClass":"pl-ent"},{"start":493,"end":494,"cssClass":"pl-kos"},{"start":501,"end":503,"cssClass":"pl-kos"},{"start":503,"end":506,"cssClass":"pl-ent"},{"start":506,"end":507,"cssClass":"pl-kos"},{"start":507,"end":509,"cssClass":"pl-kos"},{"start":509,"end":512,"cssClass":"pl-ent"},{"start":512,"end":513,"cssClass":"pl-kos"},{"start":513,"end":515,"cssClass":"pl-kos"},{"start":515,"end":518,"cssClass":"pl-ent"},{"start":518,"end":519,"cssClass":"pl-kos"},{"start":519,"end":521,"cssClass":"pl-kos"},{"start":521,"end":524,"cssClass":"pl-ent"},{"start":524,"end":525,"cssClass":"pl-kos"},{"start":525,"end":526,"cssClass":"pl-kos"},{"start":526,"end":529,"cssClass":"pl-ent"},{"start":530,"end":535,"cssClass":"pl-c1"},{"start":537,"end":546,"cssClass":"pl-s"},{"start":547,"end":548,"cssClass":"pl-kos"},{"start":548,"end":549,"cssClass":"pl-kos"},{"start":549,"end":552,"cssClass":"pl-ent"},{"start":553,"end":558,"cssClass":"pl-c1"},{"start":560,"end":567,"cssClass":"pl-s"},{"start":568,"end":569,"cssClass":"pl-kos"},{"start":569,"end":570,"cssClass":"pl-kos"},{"start":570,"end":573,"cssClass":"pl-ent"},{"start":574,"end":579,"cssClass":"pl-c1"},{"start":581,"end":607,"cssClass":"pl-s"},{"start":608,"end":609,"cssClass":"pl-kos"},{"start":609,"end":610,"cssClass":"pl-kos"},{"start":610,"end":615,"cssClass":"pl-ent"},{"start":616,"end":621,"cssClass":"pl-c1"},{"start":623,"end":665,"cssClass":"pl-s"},{"start":667,"end":669,"cssClass":"pl-c1"},{"start":671,"end":688,"cssClass":"pl-s"},{"start":690,"end":694,"cssClass":"pl-c1"},{"start":696,"end":704,"cssClass":"pl-s"},{"start":705,"end":706,"cssClass":"pl-kos"},{"start":706,"end":707,"cssClass":"pl-kos"},{"start":707,"end":712,"cssClass":"pl-ent"},{"start":713,"end":716,"cssClass":"pl-c1"},{"start":718,"end":735,"cssClass":"pl-s"},{"start":737,"end":742,"cssClass":"pl-c1"},{"start":744,"end":791,"cssClass":"pl-s"},{"start":792,"end":793,"cssClass":"pl-kos"},{"start":807,"end":809,"cssClass":"pl-kos"},{"start":809,"end":814,"cssClass":"pl-ent"},{"start":814,"end":815,"cssClass":"pl-kos"},{"start":815,"end":816,"cssClass":"pl-kos"},{"start":816,"end":819,"cssClass":"pl-ent"},{"start":820,"end":825,"cssClass":"pl-c1"},{"start":827,"end":849,"cssClass":"pl-s"},{"start":850,"end":851,"cssClass":"pl-kos"},{"start":851,"end":852,"cssClass":"pl-kos"},{"start":852,"end":855,"cssClass":"pl-ent"},{"start":855,"end":856,"cssClass":"pl-kos"},{"start":872,"end":874,"cssClass":"pl-kos"},{"start":874,"end":877,"cssClass":"pl-ent"},{"start":877,"end":878,"cssClass":"pl-kos"},{"start":878,"end":880,"cssClass":"pl-kos"},{"start":880,"end":883,"cssClass":"pl-ent"},{"start":883,"end":884,"cssClass":"pl-kos"},{"start":884,"end":886,"cssClass":"pl-kos"},{"start":886,"end":889,"cssClass":"pl-ent"},{"start":889,"end":890,"cssClass":"pl-kos"},{"start":890,"end":892,"cssClass":"pl-kos"},{"start":892,"end":895,"cssClass":"pl-ent"},{"start":895,"end":896,"cssClass":"pl-kos"},{"start":896,"end":898,"cssClass":"pl-kos"},{"start":898,"end":901,"cssClass":"pl-ent"},{"start":901,"end":902,"cssClass":"pl-kos"},{"start":902,"end":904,"cssClass":"pl-kos"},{"start":904,"end":907,"cssClass":"pl-ent"},{"start":907,"end":908,"cssClass":"pl-kos"},{"start":908,"end":910,"cssClass":"pl-kos"},{"start":910,"end":913,"cssClass":"pl-ent"},{"start":913,"end":914,"cssClass":"pl-kos"},{"start":914,"end":915,"cssClass":"pl-kos"},{"start":915,"end":918,"cssClass":"pl-ent"},{"start":919,"end":924,"cssClass":"pl-c1"},{"start":926,"end":942,"cssClass":"pl-s"},{"start":943,"end":944,"cssClass":"pl-kos"},{"start":944,"end":945,"cssClass":"pl-kos"},{"start":945,"end":948,"cssClass":"pl-ent"},{"start":949,"end":954,"cssClass":"pl-c1"},{"start":956,"end":963,"cssClass":"pl-s"},{"start":964,"end":965,"cssClass":"pl-kos"},{"start":965,"end":966,"cssClass":"pl-kos"},{"start":966,"end":969,"cssClass":"pl-ent"},{"start":970,"end":975,"cssClass":"pl-c1"},{"start":977,"end":995,"cssClass":"pl-s"},{"start":996,"end":997,"cssClass":"pl-kos"},{"start":997,"end":998,"cssClass":"pl-kos"},{"start":998,"end":1001,"cssClass":"pl-ent"},{"start":1002,"end":1007,"cssClass":"pl-c1"},{"start":1009,"end":1031,"cssClass":"pl-s"},{"start":1032,"end":1033,"cssClass":"pl-kos"},{"start":1033,"end":1034,"cssClass":"pl-kos"},{"start":1034,"end":1039,"cssClass":"pl-ent"},{"start":1040,"end":1045,"cssClass":"pl-c1"},{"start":1047,"end":1089,"cssClass":"pl-s"},{"start":1091,"end":1093,"cssClass":"pl-c1"},{"start":1095,"end":1112,"cssClass":"pl-s"},{"start":1114,"end":1118,"cssClass":"pl-c1"},{"start":1120,"end":1128,"cssClass":"pl-s"},{"start":1129,"end":1130,"cssClass":"pl-kos"},{"start":1130,"end":1131,"cssClass":"pl-kos"},{"start":1131,"end":1136,"cssClass":"pl-ent"},{"start":1137,"end":1140,"cssClass":"pl-c1"},{"start":1142,"end":1159,"cssClass":"pl-s"},{"start":1161,"end":1166,"cssClass":"pl-c1"},{"start":1168,"end":1215,"cssClass":"pl-s"},{"start":1216,"end":1217,"cssClass":"pl-kos"},{"start":1226,"end":1228,"cssClass":"pl-kos"},{"start":1228,"end":1233,"cssClass":"pl-ent"},{"start":1233,"end":1234,"cssClass":"pl-kos"},{"start":1234,"end":1235,"cssClass":"pl-kos"},{"start":1235,"end":1238,"cssClass":"pl-ent"},{"start":1239,"end":1244,"cssClass":"pl-c1"},{"start":1246,"end":1268,"cssClass":"pl-s"},{"start":1269,"end":1270,"cssClass":"pl-kos"},{"start":1270,"end":1271,"cssClass":"pl-kos"},{"start":1271,"end":1274,"cssClass":"pl-ent"},{"start":1274,"end":1275,"cssClass":"pl-kos"},{"start":1425,"end":1427,"cssClass":"pl-kos"},{"start":1427,"end":1430,"cssClass":"pl-ent"},{"start":1430,"end":1431,"cssClass":"pl-kos"},{"start":1431,"end":1433,"cssClass":"pl-kos"},{"start":1433,"end":1436,"cssClass":"pl-ent"},{"start":1436,"end":1437,"cssClass":"pl-kos"},{"start":1437,"end":1439,"cssClass":"pl-kos"},{"start":1439,"end":1442,"cssClass":"pl-ent"},{"start":1442,"end":1443,"cssClass":"pl-kos"},{"start":1443,"end":1445,"cssClass":"pl-kos"},{"start":1445,"end":1448,"cssClass":"pl-ent"},{"start":1448,"end":1449,"cssClass":"pl-kos"},{"start":1449,"end":1450,"cssClass":"pl-kos"},{"start":1450,"end":1453,"cssClass":"pl-ent"},{"start":1454,"end":1459,"cssClass":"pl-c1"},{"start":1461,"end":1470,"cssClass":"pl-s"},{"start":1471,"end":1472,"cssClass":"pl-kos"},{"start":1472,"end":1473,"cssClass":"pl-kos"},{"start":1473,"end":1476,"cssClass":"pl-ent"},{"start":1477,"end":1482,"cssClass":"pl-c1"},{"start":1484,"end":1491,"cssClass":"pl-s"},{"start":1492,"end":1493,"cssClass":"pl-kos"},{"start":1493,"end":1494,"cssClass":"pl-kos"},{"start":1494,"end":1497,"cssClass":"pl-ent"},{"start":1498,"end":1503,"cssClass":"pl-c1"},{"start":1505,"end":1531,"cssClass":"pl-s"},{"start":1532,"end":1533,"cssClass":"pl-kos"},{"start":1533,"end":1534,"cssClass":"pl-kos"},{"start":1534,"end":1539,"cssClass":"pl-ent"},{"start":1540,"end":1545,"cssClass":"pl-c1"},{"start":1547,"end":1589,"cssClass":"pl-s"},{"start":1591,"end":1593,"cssClass":"pl-c1"},{"start":1595,"end":1612,"cssClass":"pl-s"},{"start":1614,"end":1618,"cssClass":"pl-c1"},{"start":1620,"end":1628,"cssClass":"pl-s"},{"start":1629,"end":1630,"cssClass":"pl-kos"},{"start":1630,"end":1631,"cssClass":"pl-kos"},{"start":1631,"end":1636,"cssClass":"pl-ent"},{"start":1637,"end":1640,"cssClass":"pl-c1"},{"start":1642,"end":1659,"cssClass":"pl-s"},{"start":1661,"end":1666,"cssClass":"pl-c1"},{"start":1668,"end":1715,"cssClass":"pl-s"},{"start":1716,"end":1717,"cssClass":"pl-kos"},{"start":1728,"end":1730,"cssClass":"pl-kos"},{"start":1730,"end":1735,"cssClass":"pl-ent"},{"start":1735,"end":1736,"cssClass":"pl-kos"},{"start":1736,"end":1737,"cssClass":"pl-kos"},{"start":1737,"end":1740,"cssClass":"pl-ent"},{"start":1741,"end":1746,"cssClass":"pl-c1"},{"start":1748,"end":1770,"cssClass":"pl-s"},{"start":1771,"end":1772,"cssClass":"pl-kos"},{"start":1772,"end":1773,"cssClass":"pl-kos"},{"start":1773,"end":1776,"cssClass":"pl-ent"},{"start":1776,"end":1777,"cssClass":"pl-kos"},{"start":1788,"end":1790,"cssClass":"pl-kos"},{"start":1790,"end":1793,"cssClass":"pl-ent"},{"start":1793,"end":1794,"cssClass":"pl-kos"},{"start":1794,"end":1796,"cssClass":"pl-kos"},{"start":1796,"end":1799,"cssClass":"pl-ent"},{"start":1799,"end":1800,"cssClass":"pl-kos"},{"start":1800,"end":1802,"cssClass":"pl-kos"},{"start":1802,"end":1805,"cssClass":"pl-ent"},{"start":1805,"end":1806,"cssClass":"pl-kos"},{"start":1806,"end":1808,"cssClass":"pl-kos"},{"start":1808,"end":1811,"cssClass":"pl-ent"},{"start":1811,"end":1812,"cssClass":"pl-kos"},{"start":1812,"end":1814,"cssClass":"pl-kos"},{"start":1814,"end":1817,"cssClass":"pl-ent"},{"start":1817,"end":1818,"cssClass":"pl-kos"},{"start":1818,"end":1820,"cssClass":"pl-kos"},{"start":1820,"end":1823,"cssClass":"pl-ent"},{"start":1823,"end":1824,"cssClass":"pl-kos"},{"start":1824,"end":1826,"cssClass":"pl-kos"},{"start":1826,"end":1829,"cssClass":"pl-ent"},{"start":1829,"end":1830,"cssClass":"pl-kos"},{"start":1830,"end":1832,"cssClass":"pl-kos"},{"start":1832,"end":1835,"cssClass":"pl-ent"},{"start":1835,"end":1836,"cssClass":"pl-kos"},{"start":1836,"end":1838,"cssClass":"pl-kos"},{"start":1838,"end":1841,"cssClass":"pl-ent"},{"start":1841,"end":1842,"cssClass":"pl-kos"},{"start":1842,"end":1843,"cssClass":"pl-kos"},{"start":1843,"end":1846,"cssClass":"pl-ent"},{"start":1847,"end":1852,"cssClass":"pl-c1"},{"start":1854,"end":1861,"cssClass":"pl-s"},{"start":1862,"end":1863,"cssClass":"pl-kos"},{"start":1863,"end":1864,"cssClass":"pl-kos"},{"start":1864,"end":1867,"cssClass":"pl-ent"},{"start":1868,"end":1873,"cssClass":"pl-c1"},{"start":1875,"end":1901,"cssClass":"pl-s"},{"start":1902,"end":1903,"cssClass":"pl-kos"},{"start":1903,"end":1904,"cssClass":"pl-kos"},{"start":1904,"end":1909,"cssClass":"pl-ent"},{"start":1910,"end":1915,"cssClass":"pl-c1"},{"start":1917,"end":1959,"cssClass":"pl-s"},{"start":1961,"end":1963,"cssClass":"pl-c1"},{"start":1965,"end":1982,"cssClass":"pl-s"},{"start":1984,"end":1988,"cssClass":"pl-c1"},{"start":1990,"end":1998,"cssClass":"pl-s"},{"start":1999,"end":2000,"cssClass":"pl-kos"},{"start":2000,"end":2001,"cssClass":"pl-kos"},{"start":2001,"end":2006,"cssClass":"pl-ent"},{"start":2007,"end":2010,"cssClass":"pl-c1"},{"start":2012,"end":2029,"cssClass":"pl-s"},{"start":2031,"end":2036,"cssClass":"pl-c1"},{"start":2038,"end":2085,"cssClass":"pl-s"},{"start":2086,"end":2087,"cssClass":"pl-kos"},{"start":2108,"end":2110,"cssClass":"pl-kos"},{"start":2110,"end":2115,"cssClass":"pl-ent"},{"start":2115,"end":2116,"cssClass":"pl-kos"},{"start":2116,"end":2117,"cssClass":"pl-kos"},{"start":2117,"end":2120,"cssClass":"pl-ent"},{"start":2121,"end":2126,"cssClass":"pl-c1"},{"start":2128,"end":2150,"cssClass":"pl-s"},{"start":2151,"end":2152,"cssClass":"pl-kos"},{"start":2152,"end":2153,"cssClass":"pl-kos"},{"start":2153,"end":2156,"cssClass":"pl-ent"},{"start":2156,"end":2157,"cssClass":"pl-kos"},{"start":2192,"end":2194,"cssClass":"pl-kos"},{"start":2194,"end":2197,"cssClass":"pl-ent"},{"start":2197,"end":2198,"cssClass":"pl-kos"},{"start":2198,"end":2200,"cssClass":"pl-kos"},{"start":2200,"end":2203,"cssClass":"pl-ent"},{"start":2203,"end":2204,"cssClass":"pl-kos"},{"start":2204,"end":2206,"cssClass":"pl-kos"},{"start":2206,"end":2209,"cssClass":"pl-ent"},{"start":2209,"end":2210,"cssClass":"pl-kos"},{"start":2210,"end":2212,"cssClass":"pl-kos"},{"start":2212,"end":2215,"cssClass":"pl-ent"},{"start":2215,"end":2216,"cssClass":"pl-kos"},{"start":2216,"end":2218,"cssClass":"pl-kos"},{"start":2218,"end":2221,"cssClass":"pl-ent"},{"start":2221,"end":2222,"cssClass":"pl-kos"},{"start":2222,"end":2224,"cssClass":"pl-kos"},{"start":2224,"end":2227,"cssClass":"pl-ent"},{"start":2227,"end":2228,"cssClass":"pl-kos"},{"start":2228,"end":2230,"cssClass":"pl-kos"},{"start":2230,"end":2233,"cssClass":"pl-ent"},{"start":2233,"end":2234,"cssClass":"pl-kos"},{"start":2234,"end":2236,"cssClass":"pl-kos"},{"start":2236,"end":2239,"cssClass":"pl-ent"},{"start":2239,"end":2240,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":556,"end":558,"cssClass":"pl-kos"},{"start":558,"end":559,"cssClass":"pl-ent"},{"start":559,"end":560,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":42,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":6,"end":10,"cssClass":"pl-ent"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":54,"end":56,"cssClass":"pl-kos"},{"start":56,"end":60,"cssClass":"pl-ent"},{"start":60,"end":61,"cssClass":"pl-kos"},{"start":61,"end":63,"cssClass":"pl-kos"},{"start":63,"end":66,"cssClass":"pl-ent"},{"start":66,"end":67,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":42,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":6,"end":10,"cssClass":"pl-ent"},{"start":10,"end":11,"cssClass":"pl-kos"}],[],[],[],[],[],[],[],[],[],[],[],[],[],[{"start":19,"end":21,"cssClass":"pl-kos"},{"start":21,"end":25,"cssClass":"pl-ent"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":28,"cssClass":"pl-kos"},{"start":28,"end":31,"cssClass":"pl-ent"},{"start":31,"end":32,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":828,"end":830,"cssClass":"pl-kos"},{"start":830,"end":831,"cssClass":"pl-ent"},{"start":831,"end":832,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":32,"cssClass":"pl-s"},{"start":34,"end":39,"cssClass":"pl-c1"},{"start":41,"end":47,"cssClass":"pl-s"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":56,"cssClass":"pl-s"},{"start":57,"end":58,"cssClass":"pl-kos"},{"start":77,"end":79,"cssClass":"pl-kos"},{"start":79,"end":81,"cssClass":"pl-ent"},{"start":81,"end":82,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":16,"cssClass":"pl-s"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":4,"cssClass":"pl-ent"},{"start":5,"end":10,"cssClass":"pl-c1"},{"start":12,"end":31,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":7,"cssClass":"pl-ent"},{"start":8,"end":11,"cssClass":"pl-c1"},{"start":13,"end":66,"cssClass":"pl-s"},{"start":68,"end":73,"cssClass":"pl-c1"},{"start":75,"end":84,"cssClass":"pl-s"},{"start":86,"end":91,"cssClass":"pl-c1"},{"start":93,"end":96,"cssClass":"pl-s"},{"start":97,"end":98,"cssClass":"pl-kos"},{"start":98,"end":100,"cssClass":"pl-kos"},{"start":100,"end":101,"cssClass":"pl-ent"},{"start":101,"end":102,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":111,"end":112,"cssClass":"pl-kos"},{"start":112,"end":116,"cssClass":"pl-ent"},{"start":116,"end":117,"cssClass":"pl-kos"},{"start":124,"end":126,"cssClass":"pl-kos"},{"start":126,"end":130,"cssClass":"pl-ent"},{"start":130,"end":131,"cssClass":"pl-kos"},{"start":145,"end":146,"cssClass":"pl-kos"},{"start":146,"end":150,"cssClass":"pl-ent"},{"start":150,"end":151,"cssClass":"pl-kos"},{"start":160,"end":162,"cssClass":"pl-kos"},{"start":162,"end":166,"cssClass":"pl-ent"},{"start":166,"end":167,"cssClass":"pl-kos"},{"start":172,"end":173,"cssClass":"pl-kos"},{"start":173,"end":177,"cssClass":"pl-ent"},{"start":177,"end":178,"cssClass":"pl-kos"},{"start":184,"end":186,"cssClass":"pl-kos"},{"start":186,"end":190,"cssClass":"pl-ent"},{"start":190,"end":191,"cssClass":"pl-kos"},{"start":313,"end":314,"cssClass":"pl-kos"},{"start":314,"end":318,"cssClass":"pl-ent"},{"start":318,"end":319,"cssClass":"pl-kos"},{"start":323,"end":325,"cssClass":"pl-kos"},{"start":325,"end":329,"cssClass":"pl-ent"},{"start":329,"end":330,"cssClass":"pl-kos"},{"start":459,"end":461,"cssClass":"pl-kos"},{"start":461,"end":462,"cssClass":"pl-ent"},{"start":462,"end":463,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":23,"cssClass":"pl-s"},{"start":25,"end":30,"cssClass":"pl-c1"},{"start":32,"end":38,"cssClass":"pl-s"},{"start":39,"end":40,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":47,"cssClass":"pl-s"},{"start":48,"end":49,"cssClass":"pl-kos"},{"start":59,"end":61,"cssClass":"pl-kos"},{"start":61,"end":63,"cssClass":"pl-ent"},{"start":63,"end":64,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":354,"end":355,"cssClass":"pl-kos"},{"start":355,"end":359,"cssClass":"pl-ent"},{"start":360,"end":365,"cssClass":"pl-c1"},{"start":367,"end":378,"cssClass":"pl-s"},{"start":379,"end":380,"cssClass":"pl-kos"},{"start":387,"end":389,"cssClass":"pl-kos"},{"start":389,"end":393,"cssClass":"pl-ent"},{"start":393,"end":394,"cssClass":"pl-kos"},{"start":1322,"end":1324,"cssClass":"pl-kos"},{"start":1324,"end":1325,"cssClass":"pl-ent"},{"start":1325,"end":1326,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":968,"end":970,"cssClass":"pl-kos"},{"start":970,"end":971,"cssClass":"pl-ent"},{"start":971,"end":972,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":954,"end":955,"cssClass":"pl-kos"},{"start":955,"end":959,"cssClass":"pl-ent"},{"start":959,"end":960,"cssClass":"pl-kos"},{"start":968,"end":970,"cssClass":"pl-kos"},{"start":970,"end":974,"cssClass":"pl-ent"},{"start":974,"end":975,"cssClass":"pl-kos"},{"start":980,"end":981,"cssClass":"pl-kos"},{"start":981,"end":985,"cssClass":"pl-ent"},{"start":985,"end":986,"cssClass":"pl-kos"},{"start":992,"end":994,"cssClass":"pl-kos"},{"start":994,"end":998,"cssClass":"pl-ent"},{"start":998,"end":999,"cssClass":"pl-kos"},{"start":1008,"end":1010,"cssClass":"pl-kos"},{"start":1010,"end":1011,"cssClass":"pl-ent"},{"start":1011,"end":1012,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":1281,"end":1283,"cssClass":"pl-kos"},{"start":1283,"end":1284,"cssClass":"pl-ent"},{"start":1284,"end":1285,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":8,"cssClass":"pl-ent"},{"start":9,"end":11,"cssClass":"pl-c1"},{"start":13,"end":21,"cssClass":"pl-s"},{"start":23,"end":28,"cssClass":"pl-c1"},{"start":30,"end":36,"cssClass":"pl-s"},{"start":37,"end":38,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":3,"cssClass":"pl-ent"},{"start":4,"end":9,"cssClass":"pl-c1"},{"start":11,"end":19,"cssClass":"pl-s"},{"start":21,"end":35,"cssClass":"pl-c1"},{"start":37,"end":45,"cssClass":"pl-s"},{"start":46,"end":47,"cssClass":"pl-kos"},{"start":55,"end":57,"cssClass":"pl-kos"},{"start":57,"end":59,"cssClass":"pl-ent"},{"start":59,"end":60,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-ent"},{"start":2,"end":3,"cssClass":"pl-kos"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":37,"cssClass":"pl-ent"},{"start":37,"end":38,"cssClass":"pl-kos"},{"start":81,"end":83,"cssClass":"pl-kos"},{"start":83,"end":85,"cssClass":"pl-ent"},{"start":85,"end":86,"cssClass":"pl-kos"},{"start":213,"end":215,"cssClass":"pl-kos"},{"start":215,"end":216,"cssClass":"pl-ent"},{"start":216,"end":217,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":9,"cssClass":"pl-ent"},{"start":9,"end":10,"cssClass":"pl-kos"}],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":0,"end":21,"cssClass":"pl-c"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":7,"cssClass":"pl-ent"},{"start":8,"end":10,"cssClass":"pl-c1"},{"start":12,"end":34,"cssClass":"pl-s"},{"start":36,"end":40,"cssClass":"pl-c1"},{"start":42,"end":64,"cssClass":"pl-s"},{"start":65,"end":66,"cssClass":"pl-kos"}],[{"start":0,"end":6,"cssClass":"pl-smi"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":15,"cssClass":"pl-c1"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":16,"end":32,"cssClass":"pl-en"},{"start":32,"end":33,"cssClass":"pl-kos"},{"start":33,"end":51,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":53,"end":61,"cssClass":"pl-k"},{"start":62,"end":63,"cssClass":"pl-kos"},{"start":63,"end":68,"cssClass":"pl-s1"},{"start":68,"end":69,"cssClass":"pl-kos"},{"start":70,"end":71,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":27,"cssClass":"pl-en"},{"start":28,"end":29,"cssClass":"pl-c1"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":40,"cssClass":"pl-s1"},{"start":40,"end":41,"cssClass":"pl-kos"},{"start":42,"end":44,"cssClass":"pl-c1"},{"start":45,"end":46,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":14,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-c1"},{"start":17,"end":26,"cssClass":"pl-s1"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":39,"cssClass":"pl-en"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":40,"end":51,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":53,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":25,"cssClass":"pl-smi"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":34,"cssClass":"pl-c1"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":48,"cssClass":"pl-en"},{"start":48,"end":49,"cssClass":"pl-kos"},{"start":49,"end":55,"cssClass":"pl-s"},{"start":55,"end":56,"cssClass":"pl-kos"},{"start":56,"end":57,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":12,"cssClass":"pl-s1"},{"start":13,"end":16,"cssClass":"pl-c1"},{"start":17,"end":23,"cssClass":"pl-s"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":25,"end":26,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":26,"cssClass":"pl-en"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":40,"cssClass":"pl-s"},{"start":40,"end":41,"cssClass":"pl-kos"},{"start":41,"end":42,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":29,"cssClass":"pl-en"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":44,"cssClass":"pl-s"},{"start":44,"end":45,"cssClass":"pl-kos"},{"start":45,"end":46,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":6,"end":10,"cssClass":"pl-k"},{"start":11,"end":12,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":26,"cssClass":"pl-en"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":41,"cssClass":"pl-s"},{"start":41,"end":42,"cssClass":"pl-kos"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":29,"cssClass":"pl-en"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":43,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"},{"start":44,"end":45,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":30,"cssClass":"pl-en"},{"start":31,"end":32,"cssClass":"pl-c1"},{"start":33,"end":34,"cssClass":"pl-kos"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":36,"end":38,"cssClass":"pl-c1"},{"start":39,"end":40,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":19,"cssClass":"pl-s1"},{"start":20,"end":21,"cssClass":"pl-c1"},{"start":22,"end":28,"cssClass":"pl-smi"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":37,"cssClass":"pl-c1"},{"start":37,"end":38,"cssClass":"pl-kos"},{"start":38,"end":51,"cssClass":"pl-en"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":75,"cssClass":"pl-s"},{"start":75,"end":76,"cssClass":"pl-kos"},{"start":76,"end":77,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":19,"end":20,"cssClass":"pl-kos"}],[{"start":6,"end":25,"cssClass":"pl-en"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":35,"cssClass":"pl-s1"},{"start":35,"end":36,"cssClass":"pl-kos"},{"start":36,"end":37,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":2,"end":24,"cssClass":"pl-en"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":27,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":12,"cssClass":"pl-s1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":15,"end":18,"cssClass":"pl-s"},{"start":18,"end":19,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":22,"cssClass":"pl-k"},{"start":23,"end":29,"cssClass":"pl-smi"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":38,"cssClass":"pl-c1"},{"start":38,"end":39,"cssClass":"pl-kos"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":2,"end":10,"cssClass":"pl-s1"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":18,"cssClass":"pl-c1"},{"start":19,"end":20,"cssClass":"pl-c1"},{"start":21,"end":22,"cssClass":"pl-kos"}],[{"start":4,"end":13,"cssClass":"pl-c1"},{"start":15,"end":22,"cssClass":"pl-s"},{"start":22,"end":23,"cssClass":"pl-kos"}],[{"start":4,"end":8,"cssClass":"pl-c1"},{"start":10,"end":14,"cssClass":"pl-s1"}],[{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"}],[{"start":2,"end":10,"cssClass":"pl-s1"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":14,"cssClass":"pl-en"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":26,"cssClass":"pl-s"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":17,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-c1"},{"start":20,"end":23,"cssClass":"pl-k"},{"start":24,"end":30,"cssClass":"pl-smi"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":42,"cssClass":"pl-c1"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":43,"end":62,"cssClass":"pl-s"},{"start":62,"end":63,"cssClass":"pl-kos"},{"start":64,"end":65,"cssClass":"pl-kos"}],[{"start":4,"end":10,"cssClass":"pl-en"},{"start":12,"end":20,"cssClass":"pl-k"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":28,"cssClass":"pl-s1"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":30,"end":31,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-k"},{"start":13,"end":20,"cssClass":"pl-s1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":43,"cssClass":"pl-c1"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":11,"cssClass":"pl-s1"},{"start":11,"end":12,"cssClass":"pl-kos"},{"start":12,"end":14,"cssClass":"pl-en"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":24,"cssClass":"pl-s"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":26,"end":34,"cssClass":"pl-k"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":36,"cssClass":"pl-s1"},{"start":36,"end":37,"cssClass":"pl-kos"},{"start":38,"end":39,"cssClass":"pl-kos"}],[{"start":4,"end":20,"cssClass":"pl-c"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":20,"cssClass":"pl-s1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":28,"cssClass":"pl-c1"},{"start":28,"end":29,"cssClass":"pl-kos"}],[{"start":4,"end":23,"cssClass":"pl-c"}],[{"start":4,"end":10,"cssClass":"pl-s1"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":15,"cssClass":"pl-en"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":4,"end":22,"cssClass":"pl-c"}],[{"start":4,"end":10,"cssClass":"pl-s1"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":20,"cssClass":"pl-c1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":24,"cssClass":"pl-en"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":51,"cssClass":"pl-s"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":53,"cssClass":"pl-kos"}],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":20,"cssClass":"pl-s1"},{"start":21,"end":22,"cssClass":"pl-c1"},{"start":23,"end":29,"cssClass":"pl-s1"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":42,"cssClass":"pl-en"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":43,"end":50,"cssClass":"pl-s"},{"start":50,"end":51,"cssClass":"pl-kos"},{"start":51,"end":52,"cssClass":"pl-kos"}],[{"start":4,"end":10,"cssClass":"pl-s1"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":23,"cssClass":"pl-en"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":24,"end":31,"cssClass":"pl-s"},{"start":31,"end":32,"cssClass":"pl-kos"},{"start":33,"end":42,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":43,"end":44,"cssClass":"pl-kos"}],[{"start":4,"end":7,"cssClass":"pl-k"},{"start":8,"end":15,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":14,"cssClass":"pl-smi"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":24,"cssClass":"pl-c1"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":26,"end":27,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":25,"cssClass":"pl-en"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":42,"cssClass":"pl-s"},{"start":42,"end":43,"cssClass":"pl-kos"},{"start":44,"end":53,"cssClass":"pl-s"},{"start":53,"end":54,"cssClass":"pl-kos"},{"start":54,"end":55,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":25,"cssClass":"pl-en"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":45,"cssClass":"pl-s"},{"start":45,"end":46,"cssClass":"pl-kos"},{"start":47,"end":53,"cssClass":"pl-s"},{"start":53,"end":54,"cssClass":"pl-kos"},{"start":54,"end":55,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":25,"cssClass":"pl-en"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":41,"cssClass":"pl-s"},{"start":41,"end":42,"cssClass":"pl-kos"},{"start":43,"end":52,"cssClass":"pl-s"},{"start":52,"end":53,"cssClass":"pl-kos"},{"start":53,"end":54,"cssClass":"pl-kos"}],[{"start":6,"end":13,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-c1"},{"start":16,"end":19,"cssClass":"pl-k"},{"start":20,"end":29,"cssClass":"pl-s1"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":37,"cssClass":"pl-c1"},{"start":37,"end":38,"cssClass":"pl-kos"},{"start":38,"end":44,"cssClass":"pl-s1"},{"start":44,"end":45,"cssClass":"pl-kos"}],[{"start":8,"end":9,"cssClass":"pl-kos"},{"start":10,"end":17,"cssClass":"pl-c1"},{"start":19,"end":27,"cssClass":"pl-s"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":10,"end":21,"cssClass":"pl-c1"},{"start":23,"end":49,"cssClass":"pl-s"},{"start":49,"end":50,"cssClass":"pl-kos"}],[{"start":10,"end":16,"cssClass":"pl-c1"},{"start":18,"end":19,"cssClass":"pl-kos"},{"start":19,"end":20,"cssClass":"pl-c1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":22,"end":23,"cssClass":"pl-c1"},{"start":23,"end":24,"cssClass":"pl-c1"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":6,"end":13,"cssClass":"pl-s1"},{"start":13,"end":14,"cssClass":"pl-kos"},{"start":14,"end":18,"cssClass":"pl-en"},{"start":18,"end":19,"cssClass":"pl-kos"},{"start":19,"end":20,"cssClass":"pl-kos"},{"start":20,"end":21,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":4,"end":14,"cssClass":"pl-en"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":23,"cssClass":"pl-k"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":26,"end":27,"cssClass":"pl-kos"}],[{"start":6,"end":8,"cssClass":"pl-k"},{"start":9,"end":10,"cssClass":"pl-kos"},{"start":10,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":19,"end":20,"cssClass":"pl-kos"}],[{"start":8,"end":15,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":16,"end":20,"cssClass":"pl-en"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":22,"cssClass":"pl-kos"},{"start":22,"end":23,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":30,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":46,"cssClass":"pl-s"},{"start":46,"end":47,"cssClass":"pl-kos"},{"start":47,"end":48,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":30,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":47,"cssClass":"pl-s"},{"start":47,"end":48,"cssClass":"pl-kos"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":30,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":50,"cssClass":"pl-s"},{"start":50,"end":51,"cssClass":"pl-kos"},{"start":51,"end":52,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":25,"cssClass":"pl-en"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":33,"cssClass":"pl-s"},{"start":33,"end":34,"cssClass":"pl-kos"},{"start":35,"end":47,"cssClass":"pl-s1"},{"start":47,"end":48,"cssClass":"pl-kos"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-kos"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":29,"cssClass":"pl-en"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":56,"cssClass":"pl-s"},{"start":56,"end":57,"cssClass":"pl-kos"},{"start":57,"end":58,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":7,"end":11,"cssClass":"pl-c1"},{"start":11,"end":12,"cssClass":"pl-kos"},{"start":12,"end":13,"cssClass":"pl-kos"}],[{"start":4,"end":27,"cssClass":"pl-c"}],[{"start":4,"end":5,"cssClass":"pl-s1"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":6,"end":20,"cssClass":"pl-en"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":22,"cssClass":"pl-kos"},{"start":22,"end":23,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"},{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":10,"cssClass":"pl-k"},{"start":11,"end":21,"cssClass":"pl-en"},{"start":21,"end":22,"cssClass":"pl-kos"},{"start":22,"end":24,"cssClass":"pl-s1"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":26,"end":35,"cssClass":"pl-s1"},{"start":35,"end":36,"cssClass":"pl-kos"},{"start":37,"end":38,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":20,"cssClass":"pl-kos"}],[{"start":6,"end":15,"cssClass":"pl-c1"},{"start":17,"end":21,"cssClass":"pl-c1"},{"start":21,"end":22,"cssClass":"pl-kos"}],[{"start":6,"end":13,"cssClass":"pl-c1"},{"start":15,"end":24,"cssClass":"pl-s1"},{"start":24,"end":25,"cssClass":"pl-kos"}],[{"start":6,"end":14,"cssClass":"pl-c1"},{"start":16,"end":19,"cssClass":"pl-c1"},{"start":19,"end":20,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":16,"cssClass":"pl-c1"},{"start":16,"end":17,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":18,"cssClass":"pl-c1"},{"start":18,"end":19,"cssClass":"pl-kos"}],[{"start":6,"end":14,"cssClass":"pl-en"},{"start":16,"end":24,"cssClass":"pl-k"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":27,"cssClass":"pl-s1"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":29,"end":30,"cssClass":"pl-kos"}],[{"start":10,"end":16,"cssClass":"pl-k"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":19,"end":20,"cssClass":"pl-kos"},{"start":20,"end":33,"cssClass":"pl-c1"},{"start":33,"end":34,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":8,"cssClass":"pl-kos"}],[{"start":6,"end":17,"cssClass":"pl-c1"},{"start":19,"end":23,"cssClass":"pl-c1"},{"start":23,"end":24,"cssClass":"pl-kos"}],[{"start":6,"end":23,"cssClass":"pl-c1"},{"start":25,"end":27,"cssClass":"pl-c1"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-c1"},{"start":13,"end":21,"cssClass":"pl-s"},{"start":21,"end":22,"cssClass":"pl-kos"}],[{"start":6,"end":15,"cssClass":"pl-c1"},{"start":17,"end":31,"cssClass":"pl-s"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":6,"cssClass":"pl-kos"}],[{"start":4,"end":10,"cssClass":"pl-smi"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":11,"end":16,"cssClass":"pl-en"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":17,"end":19,"cssClass":"pl-s1"},{"start":19,"end":20,"cssClass":"pl-kos"},{"start":21,"end":27,"cssClass":"pl-s1"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":28,"end":29,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":25,"cssClass":"pl-smi"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":34,"cssClass":"pl-c1"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":51,"cssClass":"pl-en"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":75,"cssClass":"pl-s"},{"start":75,"end":76,"cssClass":"pl-kos"},{"start":76,"end":77,"cssClass":"pl-kos"}],[{"start":2,"end":5,"cssClass":"pl-k"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":10,"cssClass":"pl-k"},{"start":11,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-c1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":16,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":18,"end":26,"cssClass":"pl-s1"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":33,"cssClass":"pl-c1"},{"start":33,"end":34,"cssClass":"pl-kos"},{"start":35,"end":36,"cssClass":"pl-s1"},{"start":36,"end":38,"cssClass":"pl-c1"},{"start":38,"end":39,"cssClass":"pl-kos"},{"start":40,"end":41,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":13,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-c1"},{"start":16,"end":24,"cssClass":"pl-s1"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":26,"cssClass":"pl-s1"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":4,"end":14,"cssClass":"pl-en"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":15,"end":18,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-kos"},{"start":20,"end":28,"cssClass":"pl-k"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":31,"end":32,"cssClass":"pl-kos"}],[{"start":6,"end":46,"cssClass":"pl-c"}],[{"start":6,"end":9,"cssClass":"pl-k"},{"start":10,"end":14,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-c1"},{"start":17,"end":20,"cssClass":"pl-s1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":33,"cssClass":"pl-en"},{"start":33,"end":34,"cssClass":"pl-kos"},{"start":34,"end":54,"cssClass":"pl-s"},{"start":54,"end":55,"cssClass":"pl-kos"},{"start":56,"end":58,"cssClass":"pl-c1"},{"start":59,"end":62,"cssClass":"pl-s1"},{"start":62,"end":63,"cssClass":"pl-kos"},{"start":63,"end":75,"cssClass":"pl-en"},{"start":75,"end":76,"cssClass":"pl-kos"},{"start":76,"end":82,"cssClass":"pl-s"},{"start":82,"end":83,"cssClass":"pl-kos"},{"start":83,"end":84,"cssClass":"pl-kos"}],[{"start":6,"end":9,"cssClass":"pl-k"},{"start":10,"end":11,"cssClass":"pl-kos"},{"start":12,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":22,"cssClass":"pl-k"},{"start":23,"end":26,"cssClass":"pl-c1"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":31,"cssClass":"pl-s1"},{"start":31,"end":32,"cssClass":"pl-kos"},{"start":32,"end":33,"cssClass":"pl-kos"},{"start":33,"end":37,"cssClass":"pl-c1"},{"start":37,"end":38,"cssClass":"pl-kos"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":41,"end":46,"cssClass":"pl-k"},{"start":47,"end":48,"cssClass":"pl-kos"},{"start":48,"end":49,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-k"},{"start":12,"end":14,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-c1"},{"start":17,"end":21,"cssClass":"pl-s1"},{"start":21,"end":22,"cssClass":"pl-kos"},{"start":22,"end":29,"cssClass":"pl-en"},{"start":29,"end":30,"cssClass":"pl-kos"},{"start":30,"end":37,"cssClass":"pl-pds"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":31,"end":32,"cssClass":"pl-cce"},{"start":33,"end":35,"cssClass":"pl-cce"},{"start":36,"end":37,"cssClass":"pl-c1"},{"start":37,"end":38,"cssClass":"pl-kos"},{"start":39,"end":41,"cssClass":"pl-s"},{"start":41,"end":42,"cssClass":"pl-kos"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-k"},{"start":12,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":25,"cssClass":"pl-smi"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":34,"cssClass":"pl-c1"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":49,"cssClass":"pl-en"},{"start":49,"end":50,"cssClass":"pl-kos"},{"start":50,"end":52,"cssClass":"pl-s1"},{"start":52,"end":53,"cssClass":"pl-kos"},{"start":53,"end":54,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-k"},{"start":13,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":18,"end":27,"cssClass":"pl-c1"},{"start":27,"end":28,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":2,"end":7,"cssClass":"pl-k"},{"start":8,"end":17,"cssClass":"pl-en"},{"start":18,"end":19,"cssClass":"pl-c1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":23,"cssClass":"pl-s1"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":25,"end":27,"cssClass":"pl-c1"},{"start":28,"end":29,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":18,"cssClass":"pl-s1"},{"start":19,"end":20,"cssClass":"pl-c1"},{"start":21,"end":23,"cssClass":"pl-s1"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":24,"end":37,"cssClass":"pl-c1"},{"start":37,"end":38,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":16,"cssClass":"pl-s1"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":18,"end":19,"cssClass":"pl-kos"}],[{"start":6,"end":11,"cssClass":"pl-k"},{"start":12,"end":17,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-c1"},{"start":20,"end":28,"cssClass":"pl-s1"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":36,"cssClass":"pl-c1"},{"start":36,"end":37,"cssClass":"pl-kos"},{"start":37,"end":42,"cssClass":"pl-c1"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":6,"end":8,"cssClass":"pl-k"},{"start":9,"end":10,"cssClass":"pl-kos"},{"start":10,"end":15,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":17,"end":18,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":16,"cssClass":"pl-kos"}],[{"start":12,"end":13,"cssClass":"pl-kos"}],[{"start":10,"end":15,"cssClass":"pl-c1"},{"start":17,"end":22,"cssClass":"pl-s1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":28,"cssClass":"pl-en"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":32,"cssClass":"pl-s"},{"start":32,"end":33,"cssClass":"pl-kos"}],[{"start":8,"end":9,"cssClass":"pl-kos"},{"start":9,"end":10,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"},{"start":8,"end":12,"cssClass":"pl-k"},{"start":13,"end":14,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":24,"cssClass":"pl-en"},{"start":24,"end":25,"cssClass":"pl-kos"},{"start":25,"end":27,"cssClass":"pl-s1"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":28,"end":41,"cssClass":"pl-c1"},{"start":41,"end":42,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"},{"start":6,"end":10,"cssClass":"pl-k"},{"start":11,"end":12,"cssClass":"pl-kos"}],[{"start":6,"end":12,"cssClass":"pl-k"},{"start":13,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"},{"start":3,"end":4,"cssClass":"pl-kos"}],[{"start":2,"end":5,"cssClass":"pl-k"},{"start":6,"end":16,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":19,"end":25,"cssClass":"pl-smi"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":34,"cssClass":"pl-c1"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":51,"cssClass":"pl-en"},{"start":51,"end":52,"cssClass":"pl-kos"},{"start":52,"end":77,"cssClass":"pl-s"},{"start":77,"end":78,"cssClass":"pl-kos"},{"start":78,"end":79,"cssClass":"pl-kos"}],[{"start":2,"end":5,"cssClass":"pl-k"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":10,"cssClass":"pl-k"},{"start":11,"end":12,"cssClass":"pl-s1"},{"start":12,"end":13,"cssClass":"pl-c1"},{"start":13,"end":14,"cssClass":"pl-c1"},{"start":14,"end":15,"cssClass":"pl-kos"},{"start":16,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-c1"},{"start":18,"end":28,"cssClass":"pl-s1"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":35,"cssClass":"pl-c1"},{"start":35,"end":36,"cssClass":"pl-kos"},{"start":37,"end":38,"cssClass":"pl-s1"},{"start":38,"end":40,"cssClass":"pl-c1"},{"start":40,"end":41,"cssClass":"pl-kos"},{"start":42,"end":43,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":13,"cssClass":"pl-s1"},{"start":14,"end":15,"cssClass":"pl-c1"},{"start":16,"end":26,"cssClass":"pl-s1"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":28,"cssClass":"pl-s1"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":29,"end":30,"cssClass":"pl-kos"}],[{"start":4,"end":9,"cssClass":"pl-k"},{"start":10,"end":18,"cssClass":"pl-s1"},{"start":19,"end":20,"cssClass":"pl-c1"},{"start":21,"end":30,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":34,"cssClass":"pl-s1"},{"start":34,"end":35,"cssClass":"pl-kos"},{"start":35,"end":36,"cssClass":"pl-kos"}],[{"start":4,"end":6,"cssClass":"pl-k"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":16,"cssClass":"pl-s1"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":18,"end":19,"cssClass":"pl-kos"}],[{"start":6,"end":16,"cssClass":"pl-en"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":17,"end":25,"cssClass":"pl-s1"},{"start":25,"end":26,"cssClass":"pl-kos"},{"start":26,"end":28,"cssClass":"pl-c1"},{"start":28,"end":29,"cssClass":"pl-kos"},{"start":30,"end":38,"cssClass":"pl-k"},{"start":38,"end":39,"cssClass":"pl-kos"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":41,"end":42,"cssClass":"pl-kos"}],[{"start":8,"end":11,"cssClass":"pl-k"},{"start":12,"end":17,"cssClass":"pl-s1"},{"start":18,"end":19,"cssClass":"pl-c1"},{"start":20,"end":26,"cssClass":"pl-smi"},{"start":26,"end":27,"cssClass":"pl-kos"},{"start":27,"end":35,"cssClass":"pl-c1"},{"start":35,"end":36,"cssClass":"pl-kos"},{"start":36,"end":49,"cssClass":"pl-en"},{"start":49,"end":50,"cssClass":"pl-kos"},{"start":50,"end":55,"cssClass":"pl-s"},{"start":55,"end":56,"cssClass":"pl-kos"},{"start":56,"end":57,"cssClass":"pl-kos"}],[{"start":8,"end":16,"cssClass":"pl-s1"},{"start":16,"end":17,"cssClass":"pl-kos"},{"start":17,"end":22,"cssClass":"pl-c1"},{"start":22,"end":23,"cssClass":"pl-kos"},{"start":23,"end":30,"cssClass":"pl-en"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":39,"cssClass":"pl-k"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":40,"end":44,"cssClass":"pl-s1"},{"start":44,"end":45,"cssClass":"pl-kos"},{"start":46,"end":47,"cssClass":"pl-kos"}],[{"start":10,"end":13,"cssClass":"pl-k"},{"start":14,"end":21,"cssClass":"pl-s1"},{"start":22,"end":23,"cssClass":"pl-c1"},{"start":24,"end":30,"cssClass":"pl-smi"},{"start":30,"end":31,"cssClass":"pl-kos"},{"start":31,"end":39,"cssClass":"pl-c1"},{"start":39,"end":40,"cssClass":"pl-kos"},{"start":40,"end":53,"cssClass":"pl-en"},{"start":53,"end":54,"cssClass":"pl-kos"},{"start":54,"end":59,"cssClass":"pl-s"},{"start":59,"end":60,"cssClass":"pl-kos"},{"start":60,"end":61,"cssClass":"pl-kos"}],[{"start":10,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":18,"end":27,"cssClass":"pl-c1"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":28,"end":31,"cssClass":"pl-en"},{"start":31,"end":32,"cssClass":"pl-kos"},{"start":32,"end":48,"cssClass":"pl-s"},{"start":48,"end":49,"cssClass":"pl-kos"},{"start":49,"end":50,"cssClass":"pl-kos"}],[{"start":10,"end":17,"cssClass":"pl-s1"},{"start":17,"end":18,"cssClass":"pl-kos"},{"start":18,"end":27,"cssClass":"pl-c1"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":28,"end":31,"cssClass":"pl-en"},{"start":31,"end":32,"cssClass":"pl-kos"},{"start":32,"end":43,"cssClass":"pl-s"},{"start":43,"end":44,"cssClass":"pl-kos"},{"start":44,"end":45,"cssClass":"pl-kos"}],[{"start":10,"end":13,"cssClass":"pl-k"},{"start":14,"end":23,"cssClass":"pl-s1"},{"start":24,"end":25,"cssClass":"pl-c1"},{"start":26,"end":32,"cssClass":"pl-smi"},{"start":32,"end":33,"cssClass":"pl-kos"},{"start":33,"end":41,"cssClass":"pl-c1"},{"start":41,"end":42,"cssClass":"pl-kos"},{"start":42,"end":56,"cssClass":"pl-en"},{"start":56,"end":57,"cssClass":"pl-kos"},{"start":57,"end":63,"cssClass":"pl-s"},{"start":64,"end":65,"cssClass":"pl-c1"},{"start":66,"end":70,"cssClass":"pl-s1"},{"start":70,"end":71,"cssClass":"pl-kos"},{"start":71,"end":72,"cssClass":"pl-kos"}],[{"start":10,"end":12,"cssClass":"pl-k"},{"start":13,"end":14,"cssClass":"pl-kos"},{"start":14,"end":23,"cssClass":"pl-s1"},{"start":23,"end":24,"cssClass":"pl-kos"},{"start":25,"end":26,"cssClass":"pl-kos"}],[{"start":12,"end":19,"cssClass":"pl-s1"},{"start":19,"end":20,"cssClass":"pl-kos"},{"start":20,"end":29,"cssClass":"pl-c1"},{"start":30,"end":31,"cssClass":"pl-c1"},{"start":32,"end":41,"cssClass":"pl-s1"},{"start":41,"end":42,"cssClass":"pl-kos"},{"start":42,"end":51,"cssClass":"pl-c1"},{"start":51,"end":52,"cssClass":"pl-kos"}],[{"start":10,"end":11,"cssClass":"pl-kos"}],[{"start":10,"end":15,"cssClass":"pl-s1"},{"start":15,"end":16,"cssClass":"pl-kos"},{"start":16,"end":27,"cssClass":"pl-en"},{"start":27,"end":28,"cssClass":"pl-kos"},{"start":28,"end":35,"cssClass":"pl-s1"},{"start":35,"end":36,"cssClass":"pl-kos"},{"start":36,"end":37,"cssClass":"pl-kos"}],[{"start":8,"end":9,"cssClass":"pl-kos"},{"start":9,"end":10,"cssClass":"pl-kos"},{"start":10,"end":11,"cssClass":"pl-kos"}],[{"start":8,"end":14,"cssClass":"pl-k"},{"start":15,"end":20,"cssClass":"pl-s1"},{"start":20,"end":21,"cssClass":"pl-kos"},{"start":21,"end":30,"cssClass":"pl-c1"},{"start":30,"end":31,"cssClass":"pl-kos"}],[{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":8,"cssClass":"pl-kos"},{"start":8,"end":9,"cssClass":"pl-kos"}],[{"start":4,"end":5,"cssClass":"pl-kos"}],[{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":0,"end":1,"cssClass":"pl-kos"},{"start":1,"end":2,"cssClass":"pl-kos"},{"start":2,"end":3,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":8,"cssClass":"pl-ent"},{"start":8,"end":9,"cssClass":"pl-kos"}],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":5,"cssClass":"pl-ent"},{"start":5,"end":6,"cssClass":"pl-kos"},{"start":7,"end":24,"cssClass":"pl-c"}],[],[],[],[{"start":0,"end":2,"cssClass":"pl-kos"},{"start":2,"end":6,"cssClass":"pl-ent"},{"start":6,"end":7,"cssClass":"pl-kos"},{"start":7,"end":9,"cssClass":"pl-kos"},{"start":9,"end":13,"cssClass":"pl-ent"},{"start":13,"end":14,"cssClass":"pl-kos"}]],"csv":null,"csvError":null,"dependabotInfo":{"showConfigurationBanner":null,"configFilePath":null,"networkDependabotPath":"/hoellers-vassar-classes/final-project-group-8-1/network/updates","dismissConfigurationNoticePath":"/settings/dismiss-notice/dependabot_configuration_notice","configurationNoticeDismissed":false,"repoAlertsPath":"/hoellers-vassar-classes/final-project-group-8-1/security/dependabot","repoSecurityAndAnalysisPath":"/hoellers-vassar-classes/final-project-group-8-1/settings/security_analysis","repoOwnerIsOrg":true,"currentUserCanAdminRepo":false},"displayName":"final_report.html","displayUrl":"https://github.com/hoellers-vassar-classes/final-project-group-8-1/blob/main/report/final_report.html?raw=true","headerInfo":{"blobSize":"39 KB","deleteInfo":{"deleteTooltip":"Delete this file"},"editInfo":{"editTooltip":"Edit this file"},"ghDesktopPath":"https://desktop.github.com","gitLfsPath":null,"onBranch":true,"shortPath":"4ea3f2a","siteNavLoginPath":"/login?return_to=https%3A%2F%2Fgithub.com%2Fhoellers-vassar-classes%2Ffinal-project-group-8-1%2Fblob%2Fmain%2Freport%2Ffinal_report.html","isCSV":false,"isRichtext":false,"toc":null,"lineInfo":{"truncatedLoc":"461","truncatedSloc":"423"},"mode":"file"},"image":false,"isCodeownersFile":null,"isPlain":false,"isValidLegacyIssueTemplate":false,"issueTemplateHelpUrl":"https://docs.github.com/articles/about-issue-and-pull-request-templates","issueTemplate":null,"discussionTemplate":null,"language":"HTML","languageID":146,"large":false,"loggedIn":true,"newDiscussionPath":"/hoellers-vassar-classes/final-project-group-8-1/discussions/new","newIssuePath":"/hoellers-vassar-classes/final-project-group-8-1/issues/new","planSupportInfo":{"repoIsFork":null,"repoOwnedByCurrentUser":null,"requestFullPath":"/hoellers-vassar-classes/final-project-group-8-1/blob/main/report/final_report.html","showFreeOrgGatedFeatureMessage":null,"showPlanSupportBanner":null,"upgradeDataAttributes":null,"upgradePath":null},"publishBannersInfo":{"dismissActionNoticePath":"/settings/dismiss-notice/publish_action_from_dockerfile","dismissStackNoticePath":"/settings/dismiss-notice/publish_stack_from_file","releasePath":"/hoellers-vassar-classes/final-project-group-8-1/releases/new?marketplace=true","showPublishActionBanner":false,"showPublishStackBanner":false},"renderImageOrRaw":false,"richText":null,"renderedFileInfo":null,"shortPath":null,"tabSize":8,"topBannersInfo":{"overridingGlobalFundingFile":false,"globalPreferredFundingPath":null,"repoOwner":"hoellers-vassar-classes","repoName":"final-project-group-8-1","showInvalidCitationWarning":false,"citationHelpUrl":"https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files","showDependabotConfigurationBanner":null,"actionsOnboardingTip":null},"truncated":false,"viewable":true,"workflowRedirectUrl":null,"symbols":{"timedOut":false,"notAnalyzed":true,"symbols":[]}},"copilotInfo":{"documentationUrl":"https://docs.github.com/copilot/overview-of-github-copilot/about-github-copilot-for-business","notices":{"codeViewPopover":{"dismissed":false,"dismissPath":"/orgs/hoellers-vassar-classes/dismiss_notice?input%5Bnotice%5D=code_view_org_copilot_popover&input%5BorganizationId%5D=123032550"}},"userAccess":{"accessAllowed":false,"hasSubscriptionEnded":false,"orgHasCFBAccess":false,"userHasCFIAccess":false,"userHasOrgs":true,"userIsOrgAdmin":false,"userIsOrgMember":true,"business":null,"featureRequestInfo":{"showFeatureRequest":true,"alreadyRequested":false,"featureName":"copilot_for_business","requestPath":"/orgs/hoellers-vassar-classes/member_feature_request"}}},"csrf_tokens":{"/hoellers-vassar-classes/final-project-group-8-1/branches":{"post":"DIT9OUXI8w_P2DHY8il83aqs02irjd40WGnXPSYJL1jK_VMytZqlPrsncs9S5vWVsrsFBSsUJz69wUAwPuz9iA"},"/repos/preferences":{"post":"a_Lv6j_JZvtXFlSvpxqBSyj3L07tYL9zdSgyxV-PwH8sEnXj7cLDquzLxazLPApr5cZTCEkY-pMochOEBGFlrg"}}},"title":"final-project-group-8-1/report/final_report.html at main · hoellers-vassar-classes/final-project-group-8-1"}